<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Errors;

use Moov\MoovPhp\Utils;
class AccountTerminalApplicationError
{
    /**
     *
     * @var ?string $terminalApplicationID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('terminalApplicationID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $terminalApplicationID = null;

    /**
     * @param  ?string  $terminalApplicationID
     * @phpstan-pure
     */
    public function __construct(?string $terminalApplicationID = null)
    {
        $this->terminalApplicationID = $terminalApplicationID;
    }

    public function toException(): AccountTerminalApplicationErrorThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new AccountTerminalApplicationErrorThrowable($message, (int) $code, $this);
    }
}