<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Errors;

use Moov\MoovPhp\Utils;
class AddCapabilitiesError
{
    /**
     *
     * @var ?string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $error = null;

    /**
     * $capabilities
     *
     * @var ?array<string, string> $capabilities
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('capabilities')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $capabilities = null;

    /**
     * @param  ?string  $error
     * @param  ?array<string, string>  $capabilities
     * @phpstan-pure
     */
    public function __construct(?string $error = null, ?array $capabilities = null)
    {
        $this->error = $error;
        $this->capabilities = $capabilities;
    }

    public function toException(): AddCapabilitiesErrorThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new AddCapabilitiesErrorThrowable($message, (int) $code, $this);
    }
}