<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Errors;

class ClearingSimulationValidationErrorThrowable extends \RuntimeException
{
    public ClearingSimulationValidationError $container;

    public function __construct(string $message, int $statusCode, ClearingSimulationValidationError $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}