<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Errors;

use Moov\MoovPhp\Utils;
/** CreateResolutionLinkError - Describes validation errors for the create resolution link request. */
class CreateResolutionLinkError
{
    /**
     * An error with the recipient email address.
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     * An error with the recipient phone number.
     *
     * @var ?string $phone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phone = null;

    /**
     * @param  ?string  $email
     * @param  ?string  $phone
     * @phpstan-pure
     */
    public function __construct(?string $email = null, ?string $phone = null)
    {
        $this->email = $email;
        $this->phone = $phone;
    }

    public function toException(): CreateResolutionLinkErrorThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new CreateResolutionLinkErrorThrowable($message, (int) $code, $this);
    }
}