<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Errors;

use Moov\MoovPhp\Utils;
class ReceiptValidationError
{
    /**
     *
     * @var ?string $kind
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('kind')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $kind = null;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     *
     * @var ?string $emailAccountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('emailAccountID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $emailAccountID = null;

    /**
     *
     * @var ?string $forTransferID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('forTransferID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $forTransferID = null;

    /**
     *
     * @var ?string $forScheduleID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('forScheduleID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $forScheduleID = null;

    /**
     *
     * @var ?string $forOccurrenceID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('forOccurrenceID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $forOccurrenceID = null;

    /**
     * @param  ?string  $kind
     * @param  ?string  $email
     * @param  ?string  $emailAccountID
     * @param  ?string  $forTransferID
     * @param  ?string  $forScheduleID
     * @param  ?string  $forOccurrenceID
     * @phpstan-pure
     */
    public function __construct(?string $kind = null, ?string $email = null, ?string $emailAccountID = null, ?string $forTransferID = null, ?string $forScheduleID = null, ?string $forOccurrenceID = null)
    {
        $this->kind = $kind;
        $this->email = $email;
        $this->emailAccountID = $emailAccountID;
        $this->forTransferID = $forTransferID;
        $this->forScheduleID = $forScheduleID;
        $this->forOccurrenceID = $forOccurrenceID;
    }

    public function toException(): ReceiptValidationErrorThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new ReceiptValidationErrorThrowable($message, (int) $code, $this);
    }
}