<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Errors;

use Moov\MoovPhp\Utils;
class TerminalApplicationError
{
    /**
     *
     * @var ?string $platform
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('platform')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $platform = null;

    /**
     *
     * @var ?string $appBundleID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('appBundleID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $appBundleID = null;

    /**
     *
     * @var ?string $packageName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('packageName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $packageName = null;

    /**
     *
     * @var ?string $sha256Digest
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sha256Digest')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sha256Digest = null;

    /**
     *
     * @var ?string $versionCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('versionCode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $versionCode = null;

    /**
     * @param  ?string  $platform
     * @param  ?string  $appBundleID
     * @param  ?string  $packageName
     * @param  ?string  $sha256Digest
     * @param  ?string  $versionCode
     * @phpstan-pure
     */
    public function __construct(?string $platform = null, ?string $appBundleID = null, ?string $packageName = null, ?string $sha256Digest = null, ?string $versionCode = null)
    {
        $this->platform = $platform;
        $this->appBundleID = $appBundleID;
        $this->packageName = $packageName;
        $this->sha256Digest = $sha256Digest;
        $this->versionCode = $versionCode;
    }

    public function toException(): TerminalApplicationErrorThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new TerminalApplicationErrorThrowable($message, (int) $code, $this);
    }
}