<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Errors;

use Moov\MoovPhp\Utils;
class UpdateTicketError
{
    /**
     *
     * @var ?string $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $status = null;

    /**
     * @param  ?string  $status
     * @phpstan-pure
     */
    public function __construct(?string $status = null)
    {
        $this->status = $status;
    }

    public function toException(): UpdateTicketErrorThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new UpdateTicketErrorThrowable($message, (int) $code, $this);
    }
}