<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


declare(strict_types=1);

namespace Moov\MoovPhp\Hooks;


/** Available scopes for the OAuth2Auth OAuth 2.0 scheme (clientCredentials flow). */
enum OAuth2AuthOAuth2Scope: string
{

    case RootAccountsWrite = '/accounts.write';
}
