workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    latest:
        inputs:
            - location: registry.speakeasyapi.dev/moov/moov/api-latest
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/moov/moov/latest
targets:
    latest:
        target: php
        source: latest
        publish:
            packagist:
                username: moov
                token: $packagist_token
