workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    latest:
        inputs:
            - location: registry.speakeasyapi.dev/moov/moov/api-v2026.01.00
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/moov/moov/php-v2026.01.00
targets:
    latest:
        target: php
        source: latest
        publish:
            packagist:
                username: moov
                token: $packagist_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/moov/moov/v2026.01.00--php-code-samples
            labelOverride:
                fixedValue: Php (SDK)
            blocking: false
