<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Operations;

use Moov\OpenAPI\Models\Components;
use Moov\OpenAPI\Utils\SpeakeasyMetadata;
class CompleteBankAccountVerificationRequest
{
    /**
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     *
     * @var string $bankAccountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=bankAccountID')]
    public string $bankAccountID;

    /**
     *
     * @var Components\CompleteBankAccountVerification $completeBankAccountVerification
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CompleteBankAccountVerification $completeBankAccountVerification;

    /**
     * Specify an API version.
     *
     * @var ?Components\Versions $xMoovVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-moov-version')]
    public ?Components\Versions $xMoovVersion = null;

    /**
     * @param  string  $accountID
     * @param  string  $bankAccountID
     * @param  Components\CompleteBankAccountVerification  $completeBankAccountVerification
     * @param  ?Components\Versions  $xMoovVersion
     */
    public function __construct(string $accountID, string $bankAccountID, Components\CompleteBankAccountVerification $completeBankAccountVerification, ?Components\Versions $xMoovVersion = null)
    {
        $this->accountID = $accountID;
        $this->bankAccountID = $bankAccountID;
        $this->completeBankAccountVerification = $completeBankAccountVerification;
        $this->xMoovVersion = $xMoovVersion;
    }
}