<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Models\Components;
use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class CreateRepresentativeRequest
{
    /**
     * ID of the account.
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     *
     * @var \Moov\MoovPhp\Models\Components\CreateRepresentative $createRepresentative
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CreateRepresentative $createRepresentative;

    /**
     * @param  string  $accountID
     * @param  \Moov\MoovPhp\Models\Components\CreateRepresentative  $createRepresentative
     * @phpstan-pure
     */
    public function __construct(string $accountID, Components\CreateRepresentative $createRepresentative)
    {
        $this->accountID = $accountID;
        $this->createRepresentative = $createRepresentative;
    }
}