<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Models\Components;
use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class CreateInvoiceRequest
{
    /**
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     *
     * @var Components\CreateInvoice $createInvoice
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CreateInvoice $createInvoice;

    /**
     * @param  string  $accountID
     * @param  Components\CreateInvoice  $createInvoice
     * @phpstan-pure
     */
    public function __construct(string $accountID, Components\CreateInvoice $createInvoice)
    {
        $this->accountID = $accountID;
        $this->createInvoice = $createInvoice;
    }
}