<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Models\Components;
use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class CreateFeePlanAgreementsRequest
{
    /**
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     *
     * @var Components\CreateFeePlanAgreement $createFeePlanAgreement
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CreateFeePlanAgreement $createFeePlanAgreement;

    /**
     * @param  string  $accountID
     * @param  Components\CreateFeePlanAgreement  $createFeePlanAgreement
     * @phpstan-pure
     */
    public function __construct(string $accountID, Components\CreateFeePlanAgreement $createFeePlanAgreement)
    {
        $this->accountID = $accountID;
        $this->createFeePlanAgreement = $createFeePlanAgreement;
    }
}