<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Models\Components;
use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class CreateTerminalApplicationVersionRequest
{
    /**
     *
     * @var string $terminalApplicationID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=terminalApplicationID')]
    public string $terminalApplicationID;

    /**
     *
     * @var \Moov\MoovPhp\Models\Components\TerminalApplicationVersion $terminalApplicationVersion
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\TerminalApplicationVersion $terminalApplicationVersion;

    /**
     * @param  string  $terminalApplicationID
     * @param  \Moov\MoovPhp\Models\Components\TerminalApplicationVersion  $terminalApplicationVersion
     * @phpstan-pure
     */
    public function __construct(string $terminalApplicationID, Components\TerminalApplicationVersion $terminalApplicationVersion)
    {
        $this->terminalApplicationID = $terminalApplicationID;
        $this->terminalApplicationVersion = $terminalApplicationVersion;
    }
}