<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Models\Components;
use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class CreateTransferOptionsRequest
{
    /**
     * The partner's Moov account ID.
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     *
     * @var \Moov\MoovPhp\Models\Components\CreateTransferOptions $createTransferOptions
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CreateTransferOptions $createTransferOptions;

    /**
     * @param  string  $accountID
     * @param  \Moov\MoovPhp\Models\Components\CreateTransferOptions  $createTransferOptions
     * @phpstan-pure
     */
    public function __construct(string $accountID, Components\CreateTransferOptions $createTransferOptions)
    {
        $this->accountID = $accountID;
        $this->createTransferOptions = $createTransferOptions;
    }
}