<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class DeleteTerminalApplicationRequest
{
    /**
     *
     * @var string $terminalApplicationID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=terminalApplicationID')]
    public string $terminalApplicationID;

    /**
     * @param  string  $terminalApplicationID
     * @phpstan-pure
     */
    public function __construct(string $terminalApplicationID)
    {
        $this->terminalApplicationID = $terminalApplicationID;
    }
}