<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class GetAdjustmentRequest
{
    /**
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     *
     * @var string $adjustmentID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=adjustmentID')]
    public string $adjustmentID;

    /**
     * @param  string  $accountID
     * @param  string  $adjustmentID
     * @phpstan-pure
     */
    public function __construct(string $accountID, string $adjustmentID)
    {
        $this->accountID = $accountID;
        $this->adjustmentID = $adjustmentID;
    }
}