<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class GetIssuedCardTransactionRequest
{
    /**
     * The Moov business account for which cards have been issued.
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     *
     * @var string $cardTransactionID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=cardTransactionID')]
    public string $cardTransactionID;

    /**
     * @param  string  $accountID
     * @param  string  $cardTransactionID
     * @phpstan-pure
     */
    public function __construct(string $accountID, string $cardTransactionID)
    {
        $this->accountID = $accountID;
        $this->cardTransactionID = $cardTransactionID;
    }
}