<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Models\Components;
class GetPaymentMethodResponse
{
    /**
     * HTTP response content type for this operation
     *
     * @var string $contentType
     */
    public string $contentType;

    /**
     * HTTP response status code for this operation
     *
     * @var int $statusCode
     */
    public int $statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var \Psr\Http\Message\ResponseInterface $rawResponse
     */
    public \Psr\Http\Message\ResponseInterface $rawResponse;

    /**
     * $headers
     *
     * @var array<string, array<string>> $headers
     */
    public array $headers;

    /**
     * The request completed successfully.
     *
     * @var \Moov\MoovPhp\Models\Components\MoovWalletPaymentMethod|\Moov\MoovPhp\Models\Components\AchDebitFundPaymentMethod|\Moov\MoovPhp\Models\Components\AchDebitCollectPaymentMethod|\Moov\MoovPhp\Models\Components\AchCreditStandardPaymentMethod|\Moov\MoovPhp\Models\Components\AchCreditSameDayPaymentMethod|\Moov\MoovPhp\Models\Components\RtpCreditPaymentMethod|\Moov\MoovPhp\Models\Components\CardPaymentPaymentMethod|\Moov\MoovPhp\Models\Components\PushToCardPaymentMethod|\Moov\MoovPhp\Models\Components\PullFromCardPaymentMethod|\Moov\MoovPhp\Models\Components\ApplePayPaymentMethod|\Moov\MoovPhp\Models\Components\CardPresentPaymentPaymentMethod|\Moov\MoovPhp\Models\Components\InstantBankCreditPaymentMethod|\Moov\MoovPhp\Models\Components\PushToApplePayPaymentMethod|\Moov\MoovPhp\Models\Components\PullFromApplePayPaymentMethod|null $paymentMethod
     */
    public Components\MoovWalletPaymentMethod|Components\AchDebitFundPaymentMethod|Components\AchDebitCollectPaymentMethod|Components\AchCreditStandardPaymentMethod|Components\AchCreditSameDayPaymentMethod|Components\RtpCreditPaymentMethod|Components\CardPaymentPaymentMethod|Components\PushToCardPaymentMethod|Components\PullFromCardPaymentMethod|Components\ApplePayPaymentMethod|Components\CardPresentPaymentPaymentMethod|Components\InstantBankCreditPaymentMethod|Components\PushToApplePayPaymentMethod|Components\PullFromApplePayPaymentMethod|null $paymentMethod = null;

    /**
     * @param  string  $contentType
     * @param  int  $statusCode
     * @param  \Psr\Http\Message\ResponseInterface  $rawResponse
     * @param  array<string, array<string>>  $headers
     * @param  \Moov\MoovPhp\Models\Components\MoovWalletPaymentMethod|\Moov\MoovPhp\Models\Components\AchDebitFundPaymentMethod|\Moov\MoovPhp\Models\Components\AchDebitCollectPaymentMethod|\Moov\MoovPhp\Models\Components\AchCreditStandardPaymentMethod|\Moov\MoovPhp\Models\Components\AchCreditSameDayPaymentMethod|\Moov\MoovPhp\Models\Components\RtpCreditPaymentMethod|\Moov\MoovPhp\Models\Components\CardPaymentPaymentMethod|\Moov\MoovPhp\Models\Components\PushToCardPaymentMethod|\Moov\MoovPhp\Models\Components\PullFromCardPaymentMethod|\Moov\MoovPhp\Models\Components\ApplePayPaymentMethod|\Moov\MoovPhp\Models\Components\CardPresentPaymentPaymentMethod|\Moov\MoovPhp\Models\Components\InstantBankCreditPaymentMethod|\Moov\MoovPhp\Models\Components\PushToApplePayPaymentMethod|\Moov\MoovPhp\Models\Components\PullFromApplePayPaymentMethod|null  $paymentMethod
     * @phpstan-pure
     */
    public function __construct(string $contentType, int $statusCode, \Psr\Http\Message\ResponseInterface $rawResponse, Components\MoovWalletPaymentMethod|Components\AchDebitFundPaymentMethod|Components\AchDebitCollectPaymentMethod|Components\AchCreditStandardPaymentMethod|Components\AchCreditSameDayPaymentMethod|Components\RtpCreditPaymentMethod|Components\CardPaymentPaymentMethod|Components\PushToCardPaymentMethod|Components\PullFromCardPaymentMethod|Components\ApplePayPaymentMethod|Components\CardPresentPaymentPaymentMethod|Components\InstantBankCreditPaymentMethod|Components\PushToApplePayPaymentMethod|Components\PullFromApplePayPaymentMethod|null $paymentMethod = null, ?array $headers = [])
    {
        $this->contentType = $contentType;
        $this->statusCode = $statusCode;
        $this->rawResponse = $rawResponse;
        $this->headers = $headers;
        $this->paymentMethod = $paymentMethod;
    }
}