<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class GetPaymentLinkRequest
{
    /**
     * The merchant account ID.
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     *
     * @var string $paymentLinkCode
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=paymentLinkCode')]
    public string $paymentLinkCode;

    /**
     * @param  string  $accountID
     * @param  string  $paymentLinkCode
     * @phpstan-pure
     */
    public function __construct(string $accountID, string $paymentLinkCode)
    {
        $this->accountID = $accountID;
        $this->paymentLinkCode = $paymentLinkCode;
    }
}