<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class GetStatementRequest
{
    /**
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     *
     * @var string $statementID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=statementID')]
    public string $statementID;

    /**
     * @param  string  $accountID
     * @param  string  $statementID
     * @phpstan-pure
     */
    public function __construct(string $accountID, string $statementID)
    {
        $this->accountID = $accountID;
        $this->statementID = $statementID;
    }
}