<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class GetScheduledOccurrenceRequest
{
    /**
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     *
     * @var string $scheduleID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=scheduleID')]
    public string $scheduleID;

    /**
     * Allows the specification of additional filters beyond the UUID.
     *
     *
     * Specifying a UUID string returns the exact occurrence.
     * Specifying a RFC 3339 timestamp returns the latest occurrence at or before that timestamp.
     * Specifying `latest` returns the latest occurrence at or before now.
     *
     * @var string $occurrenceFilter
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=occurrenceFilter')]
    public string $occurrenceFilter;

    /**
     * Specify an API version.
     *
     *
     * API versioning follows the format `vYYYY.QQ.BB`, where 
     *   - `YYYY` is the year
     *   - `QQ` is the two-digit month for the first month of the quarter (e.g., 01, 04, 07, 10)
     *   - `BB` is the build number, starting at `.01`, for subsequent builds in the same quarter. 
     *     - For example, `v2024.01.00` is the initial release of the first quarter of 2024.
     *
     * The `latest` version represents the most recent development state. It may include breaking changes and should be treated as a beta release.
     * When no version is specified, the API defaults to `v2024.01.00`.
     *
     * @var ?string $xMoovVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Moov-Version')]
    public ?string $xMoovVersion = null;

    /**
     * @param  string  $accountID
     * @param  string  $scheduleID
     * @param  string  $occurrenceFilter
     * @param  ?string  $xMoovVersion
     * @phpstan-pure
     */
    public function __construct(string $accountID, string $scheduleID, string $occurrenceFilter, ?string $xMoovVersion = null)
    {
        $this->accountID = $accountID;
        $this->scheduleID = $scheduleID;
        $this->occurrenceFilter = $occurrenceFilter;
        $this->xMoovVersion = $xMoovVersion;
    }
}