<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class GetTransferRiskOutcomesRequest
{
    /**
     * Identifier for the transfer.
     *
     * @var string $transferID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=transferID')]
    public string $transferID;

    /**
     * The account the transfer belongs to. When omitted, the account is resolved
     *
     * from the calling credentials.
     *
     * @var ?string $xAccountID
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Account-ID')]
    public ?string $xAccountID = null;

    /**
     * @param  string  $transferID
     * @param  ?string  $xAccountID
     * @phpstan-pure
     */
    public function __construct(string $transferID, ?string $xAccountID = null)
    {
        $this->transferID = $transferID;
        $this->xAccountID = $xAccountID;
    }
}