<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Operations;

use Moov\OpenAPI\Models\Components;
use Moov\OpenAPI\Utils\SpeakeasyMetadata;
class GetWalletTransactionRequest
{
    /**
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     *
     * @var string $walletID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=walletID')]
    public string $walletID;

    /**
     *
     * @var string $transactionID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=transactionID')]
    public string $transactionID;

    /**
     * Specify an API version.
     *
     * @var ?Components\Versions $xMoovVersion
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=x-moov-version')]
    public ?Components\Versions $xMoovVersion = null;

    /**
     * @param  string  $accountID
     * @param  string  $walletID
     * @param  string  $transactionID
     * @param  ?Components\Versions  $xMoovVersion
     */
    public function __construct(string $accountID, string $walletID, string $transactionID, ?Components\Versions $xMoovVersion = null)
    {
        $this->accountID = $accountID;
        $this->walletID = $walletID;
        $this->transactionID = $transactionID;
        $this->xMoovVersion = $xMoovVersion;
    }
}