<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class ListResidualsRequest
{
    /**
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     *
     * @var ?int $skip
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=false,name=skip')]
    public ?int $skip = null;

    /**
     *
     * @var ?int $count
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=false,name=count')]
    public ?int $count = null;

    /**
     * Optional date-time to inclusively filter all residuals with a period start after this date-time.
     *
     * @var ?string $startDateTime
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=false,name=startDateTime')]
    public ?string $startDateTime = null;

    /**
     * Optional date-time to exclusively filter all residuals with a period end before this date-time.
     *
     * @var ?string $endDateTime
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=false,name=endDateTime')]
    public ?string $endDateTime = null;

    /**
     * @param  string  $accountID
     * @param  ?int  $skip
     * @param  ?int  $count
     * @param  ?string  $startDateTime
     * @param  ?string  $endDateTime
     * @phpstan-pure
     */
    public function __construct(string $accountID, ?int $skip = null, ?int $count = null, ?string $startDateTime = null, ?string $endDateTime = null)
    {
        $this->accountID = $accountID;
        $this->skip = $skip;
        $this->count = $count;
        $this->startDateTime = $startDateTime;
        $this->endDateTime = $endDateTime;
    }
}