<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class ListRefundsRequest
{
    /**
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     * Identifier for the transfer.
     *
     * @var string $transferID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=transferID')]
    public string $transferID;

    /**
     * @param  string  $accountID
     * @param  string  $transferID
     * @phpstan-pure
     */
    public function __construct(string $accountID, string $transferID)
    {
        $this->accountID = $accountID;
        $this->transferID = $transferID;
    }
}