<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Models\Components;
use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class ListPaymentMethodsRequest
{
    /**
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     * Optional parameter to filter the account's payment methods by source ID. 
     *
     *
     * A source ID can be a [walletID](https://docs.moov.io/api/sources/wallets/list/), [cardID](https://docs.moov.io/api/sources/cards/list/), 
     * or [bankAccountID](https://docs.moov.io/api/sources/bank-accounts/list/).
     *
     * @var ?string $sourceID
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=false,name=sourceID')]
    public ?string $sourceID = null;

    /**
     * Optional parameter to filter the account's payment methods by payment method type.
     *
     * @var ?Components\PaymentMethodType $paymentMethodType
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=false,name=paymentMethodType')]
    public ?Components\PaymentMethodType $paymentMethodType = null;

    /**
     * @param  string  $accountID
     * @param  ?string  $sourceID
     * @param  ?Components\PaymentMethodType  $paymentMethodType
     * @phpstan-pure
     */
    public function __construct(string $accountID, ?string $sourceID = null, ?Components\PaymentMethodType $paymentMethodType = null)
    {
        $this->accountID = $accountID;
        $this->sourceID = $sourceID;
        $this->paymentMethodType = $paymentMethodType;
    }
}