<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class ListReceiptsRequest
{
    /**
     * The transfer, schedule, or transfer occurrence ID to filter receipts by.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=false,name=id')]
    public string $id;

    /**
     * @param  string  $id
     * @phpstan-pure
     */
    public function __construct(string $id)
    {
        $this->id = $id;
    }
}