<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Operations;

use Moov\MoovPhp\Models\Components;
use Moov\MoovPhp\Utils\SpeakeasyMetadata;
class UploadDisputeEvidenceFileRequest
{
    /**
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     *
     * @var string $disputeID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=disputeID')]
    public string $disputeID;

    /**
     *
     * @var \Moov\MoovPhp\Models\Components\CreateEvidenceFileMultiPart $createEvidenceFileMultiPart
     */
    #[SpeakeasyMetadata('request:mediaType=multipart/form-data')]
    public Components\CreateEvidenceFileMultiPart $createEvidenceFileMultiPart;

    /**
     * @param  string  $accountID
     * @param  string  $disputeID
     * @param  \Moov\MoovPhp\Models\Components\CreateEvidenceFileMultiPart  $createEvidenceFileMultiPart
     * @phpstan-pure
     */
    public function __construct(string $accountID, string $disputeID, Components\CreateEvidenceFileMultiPart $createEvidenceFileMultiPart)
    {
        $this->accountID = $accountID;
        $this->disputeID = $disputeID;
        $this->createEvidenceFileMultiPart = $createEvidenceFileMultiPart;
    }
}