<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** ACHFees - A detailed breakdown of ACH fees. */
class ACHFees
{
    /**
     * Fees for standard credit transfers.
     *
     * @var BillingCountAndAmount $standardCredit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('standardCredit')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount')]
    public BillingCountAndAmount $standardCredit;

    /**
     * Fees for same-day credit transfers.
     *
     * @var BillingCountAndAmount $sameDayCredit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sameDayCredit')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount')]
    public BillingCountAndAmount $sameDayCredit;

    /**
     * Fees for debit transfers.
     *
     * @var BillingCountAndAmount $debits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('debits')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount')]
    public BillingCountAndAmount $debits;

    /**
     * Fees for authorized returns.
     *
     * @var BillingCountAndAmount $return
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('return')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount')]
    public BillingCountAndAmount $return;

    /**
     * Fees for unauthorized returns.
     *
     * @var BillingCountAndAmount $unauthorizedReturn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unauthorizedReturn')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount')]
    public BillingCountAndAmount $unauthorizedReturn;

    /**
     * Fees for notices of change.
     *
     * @var BillingCountAndAmount $noticeOfChange
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('noticeOfChange')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount')]
    public BillingCountAndAmount $noticeOfChange;

    /**
     * Fees for successful bank account verifications via Plaid or MX.
     *
     * @var BillingCountAndAmount $bankAccountVerification
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccountVerification')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount')]
    public BillingCountAndAmount $bankAccountVerification;

    /**
     * Total ACH fees.
     *
     * @var BillingCountAndAmount $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount')]
    public BillingCountAndAmount $total;

    /**
     * @param  BillingCountAndAmount  $standardCredit
     * @param  BillingCountAndAmount  $sameDayCredit
     * @param  BillingCountAndAmount  $debits
     * @param  BillingCountAndAmount  $return
     * @param  BillingCountAndAmount  $unauthorizedReturn
     * @param  BillingCountAndAmount  $noticeOfChange
     * @param  BillingCountAndAmount  $bankAccountVerification
     * @param  BillingCountAndAmount  $total
     * @phpstan-pure
     */
    public function __construct(BillingCountAndAmount $standardCredit, BillingCountAndAmount $sameDayCredit, BillingCountAndAmount $debits, BillingCountAndAmount $return, BillingCountAndAmount $unauthorizedReturn, BillingCountAndAmount $noticeOfChange, BillingCountAndAmount $bankAccountVerification, BillingCountAndAmount $total)
    {
        $this->standardCredit = $standardCredit;
        $this->sameDayCredit = $sameDayCredit;
        $this->debits = $debits;
        $this->return = $return;
        $this->unauthorizedReturn = $unauthorizedReturn;
        $this->noticeOfChange = $noticeOfChange;
        $this->bankAccountVerification = $bankAccountVerification;
        $this->total = $total;
    }
}