<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


class ACHPaymentSettingsUpdate
{
    /**
     * The description that shows up on ACH transactions. This will default to the account's display name on account creation.
     *
     * @var ?string $companyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('companyName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $companyName = null;

    /**
     * @param  ?string  $companyName
     * @phpstan-pure
     */
    public function __construct(?string $companyName = null)
    {
        $this->companyName = $companyName;
    }
}