<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


/** Adjustment - An adjustment to a wallet. */
class Adjustment
{
    /**
     *
     * @var string $adjustmentID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('adjustmentID')]
    public string $adjustmentID;

    /**
     *
     * @var string $walletID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('walletID')]
    public string $walletID;

    /**
     *
     * @var AmountDecimal $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\OpenAPI\Models\Components\AmountDecimal')]
    public AmountDecimal $amount;

    /**
     *
     * @var \DateTime $createdOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdOn')]
    public \DateTime $createdOn;

    /**
     * @param  string  $adjustmentID
     * @param  string  $walletID
     * @param  AmountDecimal  $amount
     * @param  \DateTime  $createdOn
     * @phpstan-pure
     */
    public function __construct(string $adjustmentID, string $walletID, AmountDecimal $amount, \DateTime $createdOn)
    {
        $this->adjustmentID = $adjustmentID;
        $this->walletID = $walletID;
        $this->amount = $amount;
        $this->createdOn = $createdOn;
    }
}