<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class BankAccountVerification
{
    /**
     *
     * @var \Moov\MoovPhp\Models\Components\BankAccountVerificationMethod $verificationMethod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verificationMethod')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BankAccountVerificationMethod')]
    public BankAccountVerificationMethod $verificationMethod;

    /**
     *
     * @var \Moov\MoovPhp\Models\Components\BankAccountVerificationStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BankAccountVerificationStatus')]
    public BankAccountVerificationStatus $status;

    /**
     * Reason for, and details related to, an `errored` or `verificationFailed` bank account status.
     *
     * @var ?\Moov\MoovPhp\Models\Components\BankAccountException $exceptionDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exceptionDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BankAccountException|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BankAccountException $exceptionDetails = null;

    /**
     * @param  \Moov\MoovPhp\Models\Components\BankAccountVerificationMethod  $verificationMethod
     * @param  \Moov\MoovPhp\Models\Components\BankAccountVerificationStatus  $status
     * @param  ?\Moov\MoovPhp\Models\Components\BankAccountException  $exceptionDetails
     * @phpstan-pure
     */
    public function __construct(BankAccountVerificationMethod $verificationMethod, BankAccountVerificationStatus $status, ?BankAccountException $exceptionDetails = null)
    {
        $this->verificationMethod = $verificationMethod;
        $this->status = $status;
        $this->exceptionDetails = $exceptionDetails;
    }
}