<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** BankAccountAttestationEligibility - Whether a bank account is currently eligible to receive a new attestation. */
class BankAccountAttestationEligibility
{
    /**
     * Whether the calling account is allowlisted for the attestations feature. When `false`, `eligible` is always `false`.
     *
     * @var bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    public bool $enabled;

    /**
     * Whether the bank account currently meets the requirements to receive a new attestation.
     *
     * @var bool $eligible
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('eligible')]
    public bool $eligible;

    /**
     * @param  bool  $enabled
     * @param  bool  $eligible
     * @phpstan-pure
     */
    public function __construct(bool $enabled, bool $eligible)
    {
        $this->enabled = $enabled;
        $this->eligible = $eligible;
    }
}