<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** BatchGetTransfersRequest - Array of transfer IDs to fetch. */
class BatchGetTransfersRequest
{
    /**
     * $transferIDs
     *
     * @var array<string> $transferIDs
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transferIDs')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $transferIDs;

    /**
     * @param  array<string>  $transferIDs
     * @phpstan-pure
     */
    public function __construct(array $transferIDs)
    {
        $this->transferIDs = $transferIDs;
    }
}