<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


class BrandColor
{
    /**
     * A CSS hex color representing an accent color.
     *
     * @var string $accent
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accent')]
    public string $accent;

    /**
     * @param  string  $accent
     */
    public function __construct(string $accent)
    {
        $this->accent = $accent;
    }
}