<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/**
 * Moov account capabilities.
 *
 *
 * The `production-app`, `platform.production-app`, and / or `platform.wallet-transfers` capabilities might appear in your list. These are read-only capabilities that Moov requests and uses for account verification purposes. These capabilities remains active with your account and require no additional action.
 */
enum CapabilityID: string
{
    case Transfers = 'transfers';
    case SendFunds = 'send-funds';
    case CollectFunds = 'collect-funds';
    case Wallet = 'wallet';
    case CardIssuing = 'card-issuing';
    case ProductionApp = 'production-app';
}
