<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


class CardVolumeDistribution
{
    /**
     *
     * @var int $ecommercePercentage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ecommercePercentage')]
    public int $ecommercePercentage;

    /**
     *
     * @var int $cardPresentPercentage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cardPresentPercentage')]
    public int $cardPresentPercentage;

    /**
     *
     * @var int $mailOrPhonePercentage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mailOrPhonePercentage')]
    public int $mailOrPhonePercentage;

    /**
     *
     * @var int $debtRepaymentPercentage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('debtRepaymentPercentage')]
    public int $debtRepaymentPercentage;

    /**
     * @param  int  $ecommercePercentage
     * @param  int  $cardPresentPercentage
     * @param  int  $mailOrPhonePercentage
     * @param  int  $debtRepaymentPercentage
     * @phpstan-pure
     */
    public function __construct(int $ecommercePercentage, int $cardPresentPercentage, int $mailOrPhonePercentage, int $debtRepaymentPercentage)
    {
        $this->ecommercePercentage = $ecommercePercentage;
        $this->cardPresentPercentage = $cardPresentPercentage;
        $this->mailOrPhonePercentage = $mailOrPhonePercentage;
        $this->debtRepaymentPercentage = $debtRepaymentPercentage;
    }
}