<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** CardExpiration - The expiration date of the card or token. */
class CardExpiration
{
    /**
     * Two-digit month the card expires.
     *
     * @var string $month
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('month')]
    public string $month;

    /**
     * Two-digit year the card expires.
     *
     * @var string $year
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('year')]
    public string $year;

    /**
     * @param  string  $month
     * @param  string  $year
     * @phpstan-pure
     */
    public function __construct(string $month, string $year)
    {
        $this->month = $month;
        $this->year = $year;
    }
}