<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class CardBrandFees
{
    /**
     * Total fees for this card brand.
     *
     * @var \Moov\MoovPhp\Models\Components\BillingCountAndAmount $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount')]
    public BillingCountAndAmount $total;

    /**
     * Details of interchange fees.
     *
     * @var ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount $interchange
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interchange')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BillingCountAndAmount $interchange = null;

    /**
     * A list of interchange program fees.
     *
     * @var ?array<\Moov\MoovPhp\Models\Components\BillingInterchangeProgramFee> $interchangePrograms
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interchangePrograms')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Moov\MoovPhp\Models\Components\BillingInterchangeProgramFee>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $interchangePrograms = null;

    /**
     * Details of network passthrough fees.
     *
     * @var ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount $networkPassthrough
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('networkPassthrough')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BillingCountAndAmount $networkPassthrough = null;

    /**
     * Details of completed domestic online transactions.
     *
     * @var ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount $completedDomesticOnline
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('completedDomesticOnline')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BillingCountAndAmount $completedDomesticOnline = null;

    /**
     * Details of completed domestic in-person transactions.
     *
     * @var ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount $completedDomesticInPerson
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('completedDomesticInPerson')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BillingCountAndAmount $completedDomesticInPerson = null;

    /**
     * Details of completed international online transactions.
     *
     * @var ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount $completedInternationalOnline
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('completedInternationalOnline')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BillingCountAndAmount $completedInternationalOnline = null;

    /**
     * Details of completed international in-person transactions.
     *
     * @var ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount $completedInternationalInPerson
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('completedInternationalInPerson')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BillingCountAndAmount $completedInternationalInPerson = null;

    /**
     * Details of declined transactions.
     *
     * @var ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount $declines
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('declines')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BillingCountAndAmount $declines = null;

    /**
     * Details of refunded transactions.
     *
     * @var ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount $refunds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refunds')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingCountAndAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BillingCountAndAmount $refunds = null;

    /**
     * @param  \Moov\MoovPhp\Models\Components\BillingCountAndAmount  $total
     * @param  ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount  $interchange
     * @param  ?array<\Moov\MoovPhp\Models\Components\BillingInterchangeProgramFee>  $interchangePrograms
     * @param  ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount  $networkPassthrough
     * @param  ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount  $completedDomesticOnline
     * @param  ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount  $completedDomesticInPerson
     * @param  ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount  $completedInternationalOnline
     * @param  ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount  $completedInternationalInPerson
     * @param  ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount  $declines
     * @param  ?\Moov\MoovPhp\Models\Components\BillingCountAndAmount  $refunds
     * @phpstan-pure
     */
    public function __construct(BillingCountAndAmount $total, ?BillingCountAndAmount $interchange = null, ?array $interchangePrograms = null, ?BillingCountAndAmount $networkPassthrough = null, ?BillingCountAndAmount $completedDomesticOnline = null, ?BillingCountAndAmount $completedDomesticInPerson = null, ?BillingCountAndAmount $completedInternationalOnline = null, ?BillingCountAndAmount $completedInternationalInPerson = null, ?BillingCountAndAmount $declines = null, ?BillingCountAndAmount $refunds = null)
    {
        $this->total = $total;
        $this->interchange = $interchange;
        $this->interchangePrograms = $interchangePrograms;
        $this->networkPassthrough = $networkPassthrough;
        $this->completedDomesticOnline = $completedDomesticOnline;
        $this->completedDomesticInPerson = $completedDomesticInPerson;
        $this->completedInternationalOnline = $completedInternationalOnline;
        $this->completedInternationalInPerson = $completedInternationalInPerson;
        $this->declines = $declines;
        $this->refunds = $refunds;
    }
}