<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class CollectFunds
{
    /**
     *
     * @var ?CollectFundsAch $ach
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ach')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\CollectFundsAch|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CollectFundsAch $ach = null;

    /**
     *
     * @var ?CollectFundsCardPayments $cardPayments
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cardPayments')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\CollectFundsCardPayments|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CollectFundsCardPayments $cardPayments = null;

    /**
     * @param  ?CollectFundsAch  $ach
     * @param  ?CollectFundsCardPayments  $cardPayments
     * @phpstan-pure
     */
    public function __construct(?CollectFundsAch $ach = null, ?CollectFundsCardPayments $cardPayments = null)
    {
        $this->ach = $ach;
        $this->cardPayments = $cardPayments;
    }
}