<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class CreateTransferAmountDetailsValidationError
{
    /**
     *
     * @var ?string $tip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tip')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $tip = null;

    /**
     *
     * @var ?string $tax
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $tax = null;

    /**
     * @param  ?string  $tip
     * @param  ?string  $tax
     * @phpstan-pure
     */
    public function __construct(?string $tip = null, ?string $tax = null)
    {
        $this->tip = $tip;
        $this->tax = $tax;
    }
}