<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/**
 * CreateRefund - Specifies a partial amount to refund. 
 *
 *
 * This request body is optional, an empty body will issue a refund for the full amount of the original transfer.
 */
class CreateRefund
{
    /**
     * Amount to refund in cents. If null, the original transfer's full amount will be refunded.
     *
     * @var ?int $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $amount = null;

    /**
     * Breakdown of the refunded amount.
     *
     * @var ?\Moov\MoovPhp\Models\Components\RefundAmountDetails $amountDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amountDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\RefundAmountDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?RefundAmountDetails $amountDetails = null;

    /**
     * @param  ?int  $amount
     * @param  ?\Moov\MoovPhp\Models\Components\RefundAmountDetails  $amountDetails
     * @phpstan-pure
     */
    public function __construct(?int $amount = null, ?RefundAmountDetails $amountDetails = null)
    {
        $this->amount = $amount;
        $this->amountDetails = $amountDetails;
    }
}