<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** CreateInvoiceLineItemsUpdate - A collection of line items for an invoice. */
class CreateInvoiceLineItemsUpdate
{
    /**
     * The list of line items.
     *
     * @var ?array<CreateInvoiceLineItem> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Moov\MoovPhp\Models\Components\CreateInvoiceLineItem>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $items = null;

    /**
     * @param  ?array<CreateInvoiceLineItem>  $items
     * @phpstan-pure
     */
    public function __construct(?array $items = null)
    {
        $this->items = $items;
    }
}