<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class CreateReversal
{
    /**
     * Amount to reverse in cents. Partial amounts will automatically trigger a refund instead of a cancellation.
     *
     * @var int $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public int $amount;

    /**
     * @param  int  $amount
     * @phpstan-pure
     */
    public function __construct(int $amount)
    {
        $this->amount = $amount;
    }
}