<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** CreateInvoiceLineItemOption - Represents a modifier or option applied to a line item. */
class CreateInvoiceLineItemOption
{
    /**
     * The name of the option or modifier.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * The quantity of this option.
     *
     * @var int $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    public int $quantity;

    /**
     * Optional price modification applied by this option. Can be positive, negative, or zero.
     *
     * @var ?AmountDecimal $priceModifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('priceModifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\AmountDecimal|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AmountDecimal $priceModifier = null;

    /**
     * Optional group identifier to categorize related options (e.g., 'toppings').
     *
     * @var ?string $group
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('group')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $group = null;

    /**
     * Optional list of images associated with this line item option.
     *
     * @var ?array<CreateInvoiceLineItemImage> $images
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('images')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Moov\MoovPhp\Models\Components\CreateInvoiceLineItemImage>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $images = null;

    /**
     * @param  string  $name
     * @param  int  $quantity
     * @param  ?AmountDecimal  $priceModifier
     * @param  ?string  $group
     * @param  ?array<CreateInvoiceLineItemImage>  $images
     * @phpstan-pure
     */
    public function __construct(string $name, int $quantity, ?AmountDecimal $priceModifier = null, ?string $group = null, ?array $images = null)
    {
        $this->name = $name;
        $this->quantity = $quantity;
        $this->priceModifier = $priceModifier;
        $this->group = $group;
        $this->images = $images;
    }
}