<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class CreateIndividualErrorGovernmentID
{
    /**
     *
     * @var ?CreateIndividualErrorSsn $ssn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ssn')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\CreateIndividualErrorSsn|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateIndividualErrorSsn $ssn = null;

    /**
     *
     * @var ?CreateIndividualErrorItin $itin
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('itin')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\CreateIndividualErrorItin|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateIndividualErrorItin $itin = null;

    /**
     * @param  ?CreateIndividualErrorSsn  $ssn
     * @param  ?CreateIndividualErrorItin  $itin
     * @phpstan-pure
     */
    public function __construct(?CreateIndividualErrorSsn $ssn = null, ?CreateIndividualErrorItin $itin = null)
    {
        $this->ssn = $ssn;
        $this->itin = $itin;
    }
}