<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class CreateTransferSourceCard
{
    /**
     * An optional override of the default card statement descriptor for a transfer. Accounts must be enabled by Moov to set this field.
     *
     * @var ?string $dynamicDescriptor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dynamicDescriptor')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $dynamicDescriptor = null;

    /**
     * Specifies the nature and initiator of a transaction. 
     *
     *
     * Crucial for recurring and merchant-initiated transactions as per card scheme rules. 
     * Omit for customer-initiated e-commerce transactions.
     *
     * @var ?TransactionSource $transactionSource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transactionSource')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\TransactionSource|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TransactionSource $transactionSource = null;

    /**
     * @param  ?string  $dynamicDescriptor
     * @param  ?TransactionSource  $transactionSource
     * @phpstan-pure
     */
    public function __construct(?string $dynamicDescriptor = null, ?TransactionSource $transactionSource = null)
    {
        $this->dynamicDescriptor = $dynamicDescriptor;
        $this->transactionSource = $transactionSource;
    }
}