<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


class DisputeEvidenceMetadata
{
    /**
     *
     * @var string $evidenceID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('evidenceID')]
    public string $evidenceID;

    /**
     *
     * @var string $disputeID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('disputeID')]
    public string $disputeID;

    /**
     *
     * @var string $mimeType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mimeType')]
    public string $mimeType;

    /**
     *
     * @var string $filename
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('filename')]
    public string $filename;

    /**
     *
     * @var int $size
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('size')]
    public int $size;

    /**
     *
     * @var EvidenceType $evidenceType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('evidenceType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\OpenAPI\Models\Components\EvidenceType')]
    public EvidenceType $evidenceType;

    /**
     * The text submited as evidence.
     *
     * @var string $text
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('text')]
    public string $text;

    /**
     *
     * @var \DateTime $createdOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdOn')]
    public \DateTime $createdOn;

    /**
     *
     * @var \DateTime $updatedOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedOn')]
    public \DateTime $updatedOn;

    /**
     * @param  string  $evidenceID
     * @param  string  $disputeID
     * @param  string  $mimeType
     * @param  string  $filename
     * @param  int  $size
     * @param  EvidenceType  $evidenceType
     * @param  string  $text
     * @param  \DateTime  $createdOn
     * @param  \DateTime  $updatedOn
     * @phpstan-pure
     */
    public function __construct(string $evidenceID, string $disputeID, string $mimeType, string $filename, int $size, EvidenceType $evidenceType, string $text, \DateTime $createdOn, \DateTime $updatedOn)
    {
        $this->evidenceID = $evidenceID;
        $this->disputeID = $disputeID;
        $this->mimeType = $mimeType;
        $this->filename = $filename;
        $this->size = $size;
        $this->evidenceType = $evidenceType;
        $this->text = $text;
        $this->createdOn = $createdOn;
        $this->updatedOn = $updatedOn;
    }
}