<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class Ein
{
    /**
     *
     * @var string $number
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('number')]
    public string $number;

    /**
     * @param  string  $number
     * @phpstan-pure
     */
    public function __construct(string $number)
    {
        $this->number = $number;
    }
}