<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


enum FeeCategory: string
{
    case Ach = 'ach';
    case CardAcquiring = 'card-acquiring';
    case CardOther = 'card-other';
    case CardPull = 'card-pull';
    case CardPush = 'card-push';
    case MonthlyPlatform = 'monthly-platform';
    case NetworkPassthrough = 'network-passthrough';
    case Other = 'other';
    case Rtp = 'rtp';
}
