<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


/** FeeProperties - Defines the specific parameters used for fee calculation. */
class FeeProperties
{
    /**
     * A percentage fee that is applied to the amount of each transaction in the `blended` fee model, expressed as a decimal. 
     *
     *
     * For example, 0.05% is '0.05'.
     *
     * @var ?string $variableRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('variableRate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $variableRate = null;

    /**
     * A fixed fee that is applied to the amount of each transaction in the `fixed` and `blended` fee models.
     *
     * @var ?FixedAmount $fixedAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fixedAmount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\OpenAPI\Models\Components\FixedAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?FixedAmount $fixedAmount = null;

    /**
     * Specifies the minimum allowable spending for a single transaction, working as a transaction floor.
     *
     * @var ?MinPerTransaction $minPerTransaction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('minPerTransaction')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\OpenAPI\Models\Components\MinPerTransaction|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MinPerTransaction $minPerTransaction = null;

    /**
     * Specifies the maximum allowable spending for a single transaction, working as a transaction ceiling.
     *
     * @var ?MaxPerTransaction $maxPerTransaction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maxPerTransaction')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\OpenAPI\Models\Components\MaxPerTransaction|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MaxPerTransaction $maxPerTransaction = null;

    /**
     * @param  ?string  $variableRate
     * @param  ?FixedAmount  $fixedAmount
     * @param  ?MinPerTransaction  $minPerTransaction
     * @param  ?MaxPerTransaction  $maxPerTransaction
     * @phpstan-pure
     */
    public function __construct(?string $variableRate = null, ?FixedAmount $fixedAmount = null, ?MinPerTransaction $minPerTransaction = null, ?MaxPerTransaction $maxPerTransaction = null)
    {
        $this->variableRate = $variableRate;
        $this->fixedAmount = $fixedAmount;
        $this->minPerTransaction = $minPerTransaction;
        $this->maxPerTransaction = $maxPerTransaction;
    }
}