<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** GeneratedBy - The entity that generated the fee. */
class GeneratedBy
{
    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     *
     * @var ?string $transferID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transferID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $transferID = null;

    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     *
     * @var ?string $cardID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cardID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $cardID = null;

    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     *
     * @var ?string $disputeID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('disputeID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $disputeID = null;

    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     *
     * @var ?string $accountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accountID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $accountID = null;

    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     *
     * @var ?string $bankAccountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bankAccountID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bankAccountID = null;

    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     *
     * @var ?string $invoiceID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoiceID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $invoiceID = null;

    /**
     * @param  ?string  $transferID
     * @param  ?string  $cardID
     * @param  ?string  $disputeID
     * @param  ?string  $accountID
     * @param  ?string  $bankAccountID
     * @param  ?string  $invoiceID
     * @phpstan-pure
     */
    public function __construct(?string $transferID = null, ?string $cardID = null, ?string $disputeID = null, ?string $accountID = null, ?string $bankAccountID = null, ?string $invoiceID = null)
    {
        $this->transferID = $transferID;
        $this->cardID = $cardID;
        $this->disputeID = $disputeID;
        $this->accountID = $accountID;
        $this->bankAccountID = $bankAccountID;
        $this->invoiceID = $invoiceID;
    }
}