<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


class GeneratedByTransferID
{
    /**
     *
     * @var ?string $transferID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transferID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $transferID = null;

    /**
     * @param  ?string  $transferID
     * @phpstan-pure
     */
    public function __construct(?string $transferID = null)
    {
        $this->transferID = $transferID;
    }
}