<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** GooglePayResponse - Describes a Google Pay token on a Moov account. */
class GooglePayResponse
{
    /**
     * The card brand.
     *
     * @var \Moov\MoovPhp\Models\Components\CardBrand $brand
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('brand')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\CardBrand')]
    public CardBrand $brand;

    /**
     * The last four digits of the underlying card number.
     *
     * @var string $cardDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cardDetails')]
    public string $cardDetails;

    /**
     * Uniquely identifies a linked payment card or token.
     *
     * For Apple Pay, the fingerprint is based on the tokenized card number and may vary based on the user's device.
     * This field can be used to identify specific payment methods across multiple accounts on your platform.
     *
     * @var string $fingerprint
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fingerprint')]
    public string $fingerprint;

    /**
     * The expiration date of the card or token.
     *
     * @var \Moov\MoovPhp\Models\Components\CardExpiration $expiration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expiration')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\CardExpiration')]
    public CardExpiration $expiration;

    /**
     * Country where the underlying card was issued.
     *
     * @var ?string $issuerCountry
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('issuerCountry')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $issuerCountry = null;

    /**
     * @param  \Moov\MoovPhp\Models\Components\CardBrand  $brand
     * @param  string  $cardDetails
     * @param  string  $fingerprint
     * @param  \Moov\MoovPhp\Models\Components\CardExpiration  $expiration
     * @param  ?string  $issuerCountry
     * @phpstan-pure
     */
    public function __construct(CardBrand $brand, string $cardDetails, string $fingerprint, CardExpiration $expiration, ?string $issuerCountry = null)
    {
        $this->brand = $brand;
        $this->cardDetails = $cardDetails;
        $this->fingerprint = $fingerprint;
        $this->expiration = $expiration;
        $this->issuerCountry = $issuerCountry;
    }
}