<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** GooglePayAssuranceDetails - 3-D Secure assurance details from Google Pay. */
class GooglePayAssuranceDetails
{
    /**
     * Whether the card is verified via 3-D Secure authentication.
     *
     * @var ?bool $cardHolderAuthenticated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cardHolderAuthenticated')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $cardHolderAuthenticated = null;

    /**
     * Whether the returned payment credential can be used for a transaction.
     *
     * @var ?bool $accountVerified
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accountVerified')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $accountVerified = null;

    /**
     * @param  ?bool  $cardHolderAuthenticated
     * @param  ?bool  $accountVerified
     * @phpstan-pure
     */
    public function __construct(?bool $cardHolderAuthenticated = null, ?bool $accountVerified = null)
    {
        $this->cardHolderAuthenticated = $cardHolderAuthenticated;
        $this->accountVerified = $accountVerified;
    }
}