<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/**
 * GooglePayCardInfo -   Unencrypted card metadata from
 *
 *   [CardInfo](https://developers.google.com/pay/api/web/reference/response-objects#CardInfo).
 */
class GooglePayCardInfo
{
    /**
     * The card network. One of AMEX, DISCOVER, INTERAC, JCB, MASTERCARD, VISA, or OTHER.
     *
     * @var \Moov\MoovPhp\Models\Components\CardNetwork $cardNetwork
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cardNetwork')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\CardNetwork')]
    public CardNetwork $cardNetwork;

    /**
     * The last four digits of the card number.
     *
     * @var string $cardDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cardDetails')]
    public string $cardDetails;

    /**
     * The funding source of the card. One of CREDIT, DEBIT, PREPAID, or UNKNOWN.
     *
     * @var ?\Moov\MoovPhp\Models\Components\CardFundingSource $cardFundingSource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cardFundingSource')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\CardFundingSource|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CardFundingSource $cardFundingSource = null;

    /**
     *   Billing address as returned by Google Pay.
     *
     *
     *   Refer to [Google's documentation](https://developers.google.com/pay/api/web/reference/response-objects#Address)
     *   for more information.
     *
     * @var ?\Moov\MoovPhp\Models\Components\GooglePayBillingAddress $billingAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billingAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\GooglePayBillingAddress|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?GooglePayBillingAddress $billingAddress = null;

    /**
     * 3-D Secure assurance details from Google Pay.
     *
     * @var ?\Moov\MoovPhp\Models\Components\GooglePayAssuranceDetails $assuranceDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('assuranceDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\GooglePayAssuranceDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?GooglePayAssuranceDetails $assuranceDetails = null;

    /**
     * @param  \Moov\MoovPhp\Models\Components\CardNetwork  $cardNetwork
     * @param  string  $cardDetails
     * @param  ?\Moov\MoovPhp\Models\Components\CardFundingSource  $cardFundingSource
     * @param  ?\Moov\MoovPhp\Models\Components\GooglePayBillingAddress  $billingAddress
     * @param  ?\Moov\MoovPhp\Models\Components\GooglePayAssuranceDetails  $assuranceDetails
     * @phpstan-pure
     */
    public function __construct(CardNetwork $cardNetwork, string $cardDetails, ?CardFundingSource $cardFundingSource = null, ?GooglePayBillingAddress $billingAddress = null, ?GooglePayAssuranceDetails $assuranceDetails = null)
    {
        $this->cardNetwork = $cardNetwork;
        $this->cardDetails = $cardDetails;
        $this->cardFundingSource = $cardFundingSource;
        $this->billingAddress = $billingAddress;
        $this->assuranceDetails = $assuranceDetails;
    }
}