<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class GovernmentIDError
{
    /**
     *
     * @var ?\Moov\MoovPhp\Models\Components\GovernmentIDErrorSsn $ssn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ssn')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\GovernmentIDErrorSsn|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?GovernmentIDErrorSsn $ssn = null;

    /**
     *
     * @var ?\Moov\MoovPhp\Models\Components\GovernmentIDErrorItin $itin
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('itin')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\GovernmentIDErrorItin|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?GovernmentIDErrorItin $itin = null;

    /**
     * @param  ?\Moov\MoovPhp\Models\Components\GovernmentIDErrorSsn  $ssn
     * @param  ?\Moov\MoovPhp\Models\Components\GovernmentIDErrorItin  $itin
     * @phpstan-pure
     */
    public function __construct(?GovernmentIDErrorSsn $ssn = null, ?GovernmentIDErrorItin $itin = null)
    {
        $this->ssn = $ssn;
        $this->itin = $itin;
    }
}