<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** ImageMetadata - Metadata about an uploaded image. */
class ImageMetadata
{
    /**
     *
     * @var string $imageID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('imageID')]
    public string $imageID;

    /**
     * A public URL to access the image. An optional `size={width}x{height}` 
     *
     * query parameter can be provided to resize the image.
     *
     * @var string $link
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('link')]
    public string $link;

    /**
     *
     * @var \DateTime $createdOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdOn')]
    public \DateTime $createdOn;

    /**
     *
     * @var \DateTime $updatedOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedOn')]
    public \DateTime $updatedOn;

    /**
     * Alternative text for the image.
     *
     * @var ?string $altText
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('altText')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $altText = null;

    /**
     * @param  string  $imageID
     * @param  string  $link
     * @param  \DateTime  $createdOn
     * @param  \DateTime  $updatedOn
     * @param  ?string  $altText
     * @phpstan-pure
     */
    public function __construct(string $imageID, string $link, \DateTime $createdOn, \DateTime $updatedOn, ?string $altText = null)
    {
        $this->imageID = $imageID;
        $this->link = $link;
        $this->createdOn = $createdOn;
        $this->updatedOn = $updatedOn;
        $this->altText = $altText;
    }
}