<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** IncurredFee - A fee incurred by a user. */
class IncurredFee
{
    /**
     *
     * @var ?string $feeID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('feeID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $feeID = null;

    /**
     *
     * @var ?string $accountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accountID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $accountID = null;

    /**
     *
     * @var ?string $walletID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('walletID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $walletID = null;

    /**
     *
     * @var ?\DateTime $createdOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdOn')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdOn = null;

    /**
     *
     * @var ?string $feeName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('feeName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $feeName = null;

    /**
     *
     * @var ?AmountDecimal $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\AmountDecimal|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AmountDecimal $amount = null;

    /**
     * The entity that generated the fee.
     *
     * @var ?GeneratedBy $generatedBy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('generatedBy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\GeneratedBy|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?GeneratedBy $generatedBy = null;

    /**
     *
     * @var ?string $feeGroup
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('feeGroup')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $feeGroup = null;

    /**
     *
     * @var ?string $residualID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('residualID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $residualID = null;

    /**
     * @param  ?string  $feeID
     * @param  ?string  $accountID
     * @param  ?string  $walletID
     * @param  ?\DateTime  $createdOn
     * @param  ?string  $feeName
     * @param  ?AmountDecimal  $amount
     * @param  ?GeneratedBy  $generatedBy
     * @param  ?string  $feeGroup
     * @param  ?string  $residualID
     * @phpstan-pure
     */
    public function __construct(?string $feeID = null, ?string $accountID = null, ?string $walletID = null, ?\DateTime $createdOn = null, ?string $feeName = null, ?AmountDecimal $amount = null, ?GeneratedBy $generatedBy = null, ?string $feeGroup = null, ?string $residualID = null)
    {
        $this->feeID = $feeID;
        $this->accountID = $accountID;
        $this->walletID = $walletID;
        $this->createdOn = $createdOn;
        $this->feeName = $feeName;
        $this->amount = $amount;
        $this->generatedBy = $generatedBy;
        $this->feeGroup = $feeGroup;
        $this->residualID = $residualID;
    }
}