<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/**
 * IssuedCardActivity - An issued card activity record. Each record represents the use of an issued card.
 *
 *
 * Exactly one of `authorizationID` or `cardTransactionID` is present:
 * - Activity that has an authorization request includes `authorizationID`. `cardTransactionID` is omitted.
 * - Activity that does not have a corresponding authorization request includes `cardTransactionID` and omits `authorizationID` and
 *  `authorizedAmount`.
 */
class IssuedCardActivity
{
    /**
     * Status of a card issuing authorization.
     *
     * @var \Moov\MoovPhp\Models\Components\IssuingAuthorizationStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\IssuingAuthorizationStatus')]
    public IssuingAuthorizationStatus $status;

    /**
     *
     * @var string $issuedCardID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('issuedCardID')]
    public string $issuedCardID;

    /**
     *
     * @var \DateTime $createdOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdOn')]
    public \DateTime $createdOn;

    /**
     *
     * @var \Moov\MoovPhp\Models\Components\IssuingMerchantData $merchantData
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('merchantData')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\IssuingMerchantData')]
    public IssuingMerchantData $merchantData;

    /**
     * Identifier for the authorization. Present for all activity except cleared card transactions without a corresponding authorization.
     *
     * @var ?string $authorizationID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorizationID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $authorizationID = null;

    /**
     * Identifier for the settlement card transaction. Present for cleared card transactions without a corresponding authorization.
     *
     * @var ?string $cardTransactionID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cardTransactionID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $cardTransactionID = null;

    /**
     * Last four digits of the card number.
     *
     * @var ?string $lastFourCardNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastFourCardNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $lastFourCardNumber = null;

    /**
     * Identifier for the account of the card's authorized user.
     *
     * @var ?string $authorizedUserAccountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorizedUserAccountID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $authorizedUserAccountID = null;

    /**
     * Amount authorized on the card. Omitted for cleared card transactions without a corresponding authorization.
     *
     * @var ?string $authorizedAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorizedAmount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $authorizedAmount = null;

    /**
     * Amount cleared or settled for the activity.
     *
     * @var ?string $clearedAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clearedAmount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $clearedAmount = null;

    /**
     * The reason an authorization or authorization event was declined. Only present if the
     *
     * authorization or event has been declined.
     *
     * @var ?\Moov\MoovPhp\Models\Components\IssuingDeclineReason $declineReason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('declineReason')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\IssuingDeclineReason|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?IssuingDeclineReason $declineReason = null;

    /**
     * @param  \Moov\MoovPhp\Models\Components\IssuingAuthorizationStatus  $status
     * @param  string  $issuedCardID
     * @param  \DateTime  $createdOn
     * @param  \Moov\MoovPhp\Models\Components\IssuingMerchantData  $merchantData
     * @param  ?string  $authorizationID
     * @param  ?string  $cardTransactionID
     * @param  ?string  $lastFourCardNumber
     * @param  ?string  $authorizedUserAccountID
     * @param  ?string  $authorizedAmount
     * @param  ?string  $clearedAmount
     * @param  ?\Moov\MoovPhp\Models\Components\IssuingDeclineReason  $declineReason
     * @phpstan-pure
     */
    public function __construct(IssuingAuthorizationStatus $status, string $issuedCardID, \DateTime $createdOn, IssuingMerchantData $merchantData, ?string $authorizationID = null, ?string $cardTransactionID = null, ?string $lastFourCardNumber = null, ?string $authorizedUserAccountID = null, ?string $authorizedAmount = null, ?string $clearedAmount = null, ?IssuingDeclineReason $declineReason = null)
    {
        $this->status = $status;
        $this->issuedCardID = $issuedCardID;
        $this->createdOn = $createdOn;
        $this->merchantData = $merchantData;
        $this->authorizationID = $authorizationID;
        $this->cardTransactionID = $cardTransactionID;
        $this->lastFourCardNumber = $lastFourCardNumber;
        $this->authorizedUserAccountID = $authorizedUserAccountID;
        $this->authorizedAmount = $authorizedAmount;
        $this->clearedAmount = $clearedAmount;
        $this->declineReason = $declineReason;
    }
}