<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/**
 * LinkGooglePay -   Links a Google Pay token to a Moov account.
 *
 *
 *   The `paymentMethodData` field should contain the `paymentMethodData` property from the
 *   [PaymentData](https://developers.google.com/pay/api/web/reference/response-objects#PaymentData) response
 *   returned by Google Pay's client SDK. Pass it through unmodified.
 */
class LinkGooglePay
{
    /**
     *   The merchant accountID this token was minted for. Must match the `gatewayMerchantId`
     *
     *   value passed to Google Pay when constructing the PaymentDataRequest. card-gateway validates
     *   that the decrypted `gatewayMerchantId` matches this value.
     *
     * @var string $merchantAccountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('merchantAccountID')]
    public string $merchantAccountID;

    /**
     *   The `paymentMethodData` object from Google Pay's
     *
     *   [PaymentData](https://developers.google.com/pay/api/web/reference/response-objects#PaymentData) response.
     *
     * @var \Moov\MoovPhp\Models\Components\GooglePayPaymentMethodData $paymentMethodData
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentMethodData')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\GooglePayPaymentMethodData')]
    public GooglePayPaymentMethodData $paymentMethodData;

    /**
     * @param  string  $merchantAccountID
     * @param  \Moov\MoovPhp\Models\Components\GooglePayPaymentMethodData  $paymentMethodData
     * @phpstan-pure
     */
    public function __construct(string $merchantAccountID, GooglePayPaymentMethodData $paymentMethodData)
    {
        $this->merchantAccountID = $merchantAccountID;
        $this->paymentMethodData = $paymentMethodData;
    }
}