<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


/**
 * LinkApplePaymentData -   Contains the encrypted payment data.
 *
 *
 *   Refer to [Apple's documentation](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypaymenttoken/1916115-paymentdata) 
 *   for more information.
 */
class LinkApplePaymentData
{
    /**
     * Specifies the encryption used for the payment token ("EC_v1" or "RSA_v1").
     *
     * @var string $version
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('version')]
    public string $version;

    /**
     * The encrypted, base64-encoded payment data.
     *
     * @var string $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    public string $data;

    /**
     * A base64 encoded signature of the payment and header data.
     *
     * @var string $signature
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('signature')]
    public string $signature;

    /**
     * Information needed to decrypt Apple Pay payment data.
     *
     *
     * Refer to [Apple's documentation](https://developer.apple.com/documentation/passkit/payment-token-format-reference#Header-keys-and-values) 
     * for more information.
     *
     * @var ApplePayHeader $header
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('header')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\OpenAPI\Models\Components\ApplePayHeader')]
    public ApplePayHeader $header;

    /**
     * @param  string  $version
     * @param  string  $data
     * @param  string  $signature
     * @param  ApplePayHeader  $header
     */
    public function __construct(string $version, string $data, string $signature, ApplePayHeader $header)
    {
        $this->version = $version;
        $this->data = $data;
        $this->signature = $signature;
        $this->header = $header;
    }
}