<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** MerchantEntry - Identifies a merchant by ID, descriptor pattern, or both. At least one of `networkID` or `descriptorPattern` must be set. */
class MerchantEntry
{
    /**
     * The merchant's unique identifier (ISO 8583 DE42), matched exactly.
     *
     * @var ?string $networkID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('networkID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $networkID = null;

    /**
     * A case-insensitive RE2 regular expression matched against the merchant descriptor (ISO 8583 DE43).
     *
     * @var ?string $descriptorPattern
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('descriptorPattern')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $descriptorPattern = null;

    /**
     * An optional label for this entry.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * @param  ?string  $networkID
     * @param  ?string  $descriptorPattern
     * @param  ?string  $name
     * @phpstan-pure
     */
    public function __construct(?string $networkID = null, ?string $descriptorPattern = null, ?string $name = null)
    {
        $this->networkID = $networkID;
        $this->descriptorPattern = $descriptorPattern;
        $this->name = $name;
    }
}