<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** MerchantCategories - The predefined merchant category groups available for issued card spend controls. */
class MerchantCategories
{
    /**
     * $merchantCategories
     *
     * @var array<\Moov\MoovPhp\Models\Components\MerchantCategory> $merchantCategories
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('merchantCategories')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Moov\MoovPhp\Models\Components\MerchantCategory>')]
    public array $merchantCategories;

    /**
     * @param  array<\Moov\MoovPhp\Models\Components\MerchantCategory>  $merchantCategories
     * @phpstan-pure
     */
    public function __construct(array $merchantCategories)
    {
        $this->merchantCategories = $merchantCategories;
    }
}