<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


/** Status of the completed occurrence. */
enum OccurrenceStatus: string
{
    case Pending = 'pending';
    case Failed = 'failed';
    case Completed = 'completed';
}
