<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class PartialScheduleAccount
{
    /**
     *
     * @var string $accountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accountID')]
    public string $accountID;

    /**
     *
     * @var string $displayName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('displayName')]
    public string $displayName;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     * @param  string  $accountID
     * @param  string  $displayName
     * @param  ?string  $email
     * @phpstan-pure
     */
    public function __construct(string $accountID, string $displayName, ?string $email = null)
    {
        $this->accountID = $accountID;
        $this->displayName = $displayName;
        $this->email = $email;
    }
}