<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


/** PaymentLinkDisplayOptionsUpdate - Customizable display options for a payment link. */
class PaymentLinkDisplayOptionsUpdate
{
    /**
     * The payment page title displayed to the user.
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     * A payment description displayed to the user.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * The text to be displayed on web form's submit button.
     *
     *
     * If set to "auto" the UI will automatically select between 
     * "pay" and "confirm" for payments and payouts respectively.
     *
     * @var ?CallToAction $callToAction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('callToAction')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\OpenAPI\Models\Components\CallToAction|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CallToAction $callToAction = null;

    /**
     * @param  ?string  $title
     * @param  ?string  $description
     * @param  ?CallToAction  $callToAction
     */
    public function __construct(?string $title = null, ?string $description = null, ?CallToAction $callToAction = null)
    {
        $this->title = $title;
        $this->description = $description;
        $this->callToAction = $callToAction;
    }
}