<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class PaymentLinkLineItemOptionValidationError
{
    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?string $group
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('group')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $group = null;

    /**
     *
     * @var ?AmountDecimalValidationError $priceModifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('priceModifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\AmountDecimalValidationError|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AmountDecimalValidationError $priceModifier = null;

    /**
     *
     * @var ?string $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $quantity = null;

    /**
     * @param  ?string  $name
     * @param  ?string  $group
     * @param  ?AmountDecimalValidationError  $priceModifier
     * @param  ?string  $quantity
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?string $group = null, ?AmountDecimalValidationError $priceModifier = null, ?string $quantity = null)
    {
        $this->name = $name;
        $this->group = $group;
        $this->priceModifier = $priceModifier;
        $this->quantity = $quantity;
    }
}