<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class PaymentLink
{
    /**
     * Unique code identifying this payment link.
     *
     * @var string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    public string $code;

    /**
     *
     * @var \Moov\MoovPhp\Models\Components\PaymentLinkType $paymentLinkType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentLinkType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PaymentLinkType')]
    public PaymentLinkType $paymentLinkType;

    /**
     * The operating mode for an account.
     *
     * @var \Moov\MoovPhp\Models\Components\Mode $mode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\Mode')]
    public Mode $mode;

    /**
     *
     * @var \Moov\MoovPhp\Models\Components\PaymentLinkStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PaymentLinkStatus')]
    public PaymentLinkStatus $status;

    /**
     * The partner's Moov account ID.
     *
     * @var string $partnerAccountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('partnerAccountID')]
    public string $partnerAccountID;

    /**
     * The merchant's Moov account ID.
     *
     * @var string $merchantAccountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('merchantAccountID')]
    public string $merchantAccountID;

    /**
     * The payment link's owner's Moov account ID.
     *
     * @var string $ownerAccountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ownerAccountID')]
    public string $ownerAccountID;

    /**
     * The merchant's preferred payment method ID. Must be a wallet payment method.
     *
     * @var string $merchantPaymentMethodID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('merchantPaymentMethodID')]
    public string $merchantPaymentMethodID;

    /**
     * Link to the payment landing page for this payment link.
     *
     * @var string $link
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('link')]
    public string $link;

    /**
     * The number of times this payment link has been used.
     *
     * @var int $uses
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('uses')]
    public int $uses;

    /**
     * Customizable display options for a payment link.
     *
     * @var \Moov\MoovPhp\Models\Components\PaymentLinkDisplayOptions $display
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('display')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PaymentLinkDisplayOptions')]
    public PaymentLinkDisplayOptions $display;

    /**
     *
     * @var \Moov\MoovPhp\Models\Components\PaymentLinkCustomerOptions $customer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PaymentLinkCustomerOptions')]
    public PaymentLinkCustomerOptions $customer;

    /**
     *
     * @var \DateTime $createdOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdOn')]
    public \DateTime $createdOn;

    /**
     *
     * @var \DateTime $updatedOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedOn')]
    public \DateTime $updatedOn;

    /**
     * The fixed amount of the payment link. 
     *
     *
     * In API versions before `2026.07.00`, this was a required field.
     *
     * In API version `2026.07.00` and beyond, this field is required for `fixed` payment amount types and omitted 
     * for `open` payment amount types.
     *
     * @var ?\Moov\MoovPhp\Models\Components\Amount $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\Amount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Amount $amount = null;

    /**
     * An optional limit on the number of times this payment link can be used.
     *
     *
     * **For payouts, `maxUses` is always 1.**
     *
     * @var ?int $maxUses
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maxUses')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $maxUses = null;

    /**
     * The timestamp when this payment link was last used.
     *
     * @var ?\DateTime $lastUsedOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastUsedOn')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $lastUsedOn = null;

    /**
     * An optional expiration date for this payment link.
     *
     * @var ?\DateTime $expiresOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expiresOn')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $expiresOn = null;

    /**
     * Options for payment links used to collect payment.
     *
     * @var ?\Moov\MoovPhp\Models\Components\PaymentLinkPaymentDetails $payment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PaymentLinkPaymentDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentLinkPaymentDetails $payment = null;

    /**
     *
     * @var ?\Moov\MoovPhp\Models\Components\PaymentLinkPayoutDetails $payout
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payout')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PaymentLinkPayoutDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentLinkPayoutDetails $payout = null;

    /**
     * An optional collection of line items for a payment link.
     *
     * When line items are provided, their total plus tax must equal the payment link amount.
     *
     * @var ?\Moov\MoovPhp\Models\Components\PaymentLinkLineItems $lineItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lineItems')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PaymentLinkLineItems|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentLinkLineItems $lineItems = null;

    /**
     *
     * @var ?\DateTime $disabledOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('disabledOn')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $disabledOn = null;

    /**
     *
     * @var ?\Moov\MoovPhp\Models\Components\PaymentLinkAmountDetails $amountDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amountDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PaymentLinkAmountDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentLinkAmountDetails $amountDetails = null;

    /**
     * @param  string  $code
     * @param  \Moov\MoovPhp\Models\Components\PaymentLinkType  $paymentLinkType
     * @param  \Moov\MoovPhp\Models\Components\Mode  $mode
     * @param  \Moov\MoovPhp\Models\Components\PaymentLinkStatus  $status
     * @param  string  $partnerAccountID
     * @param  string  $merchantAccountID
     * @param  string  $ownerAccountID
     * @param  string  $merchantPaymentMethodID
     * @param  string  $link
     * @param  int  $uses
     * @param  \Moov\MoovPhp\Models\Components\PaymentLinkDisplayOptions  $display
     * @param  \Moov\MoovPhp\Models\Components\PaymentLinkCustomerOptions  $customer
     * @param  \DateTime  $createdOn
     * @param  \DateTime  $updatedOn
     * @param  ?\Moov\MoovPhp\Models\Components\Amount  $amount
     * @param  ?int  $maxUses
     * @param  ?\DateTime  $lastUsedOn
     * @param  ?\DateTime  $expiresOn
     * @param  ?\Moov\MoovPhp\Models\Components\PaymentLinkPaymentDetails  $payment
     * @param  ?\Moov\MoovPhp\Models\Components\PaymentLinkPayoutDetails  $payout
     * @param  ?\Moov\MoovPhp\Models\Components\PaymentLinkLineItems  $lineItems
     * @param  ?\DateTime  $disabledOn
     * @param  ?\Moov\MoovPhp\Models\Components\PaymentLinkAmountDetails  $amountDetails
     * @phpstan-pure
     */
    public function __construct(string $code, PaymentLinkType $paymentLinkType, Mode $mode, PaymentLinkStatus $status, string $partnerAccountID, string $merchantAccountID, string $ownerAccountID, string $merchantPaymentMethodID, string $link, int $uses, PaymentLinkDisplayOptions $display, PaymentLinkCustomerOptions $customer, \DateTime $createdOn, \DateTime $updatedOn, ?Amount $amount = null, ?int $maxUses = null, ?\DateTime $lastUsedOn = null, ?\DateTime $expiresOn = null, ?PaymentLinkPaymentDetails $payment = null, ?PaymentLinkPayoutDetails $payout = null, ?PaymentLinkLineItems $lineItems = null, ?\DateTime $disabledOn = null, ?PaymentLinkAmountDetails $amountDetails = null)
    {
        $this->code = $code;
        $this->paymentLinkType = $paymentLinkType;
        $this->mode = $mode;
        $this->status = $status;
        $this->partnerAccountID = $partnerAccountID;
        $this->merchantAccountID = $merchantAccountID;
        $this->ownerAccountID = $ownerAccountID;
        $this->merchantPaymentMethodID = $merchantPaymentMethodID;
        $this->link = $link;
        $this->uses = $uses;
        $this->display = $display;
        $this->customer = $customer;
        $this->createdOn = $createdOn;
        $this->updatedOn = $updatedOn;
        $this->amount = $amount;
        $this->maxUses = $maxUses;
        $this->lastUsedOn = $lastUsedOn;
        $this->expiresOn = $expiresOn;
        $this->payment = $payment;
        $this->payout = $payout;
        $this->lineItems = $lineItems;
        $this->disabledOn = $disabledOn;
        $this->amountDetails = $amountDetails;
    }
}