<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


class PaymentLinkPayoutDetailsUpdate
{
    /**
     * A list of payment methods that should be supported for this payment link.
     *
     * @var ?array<DisbursementPaymentMethodType> $allowedMethods
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allowedMethods')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Moov\OpenAPI\Models\Components\DisbursementPaymentMethodType>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $allowedMethods = null;

    /**
     * Specify the intended recipient of the payout.
     *
     *
     * This information will be used to authenticate the end user when they follow the payment link.
     *
     * @var ?PayoutRecipientUpdate $recipient
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recipient')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\OpenAPI\Models\Components\PayoutRecipientUpdate|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PayoutRecipientUpdate $recipient = null;

    /**
     * @param  ?array<DisbursementPaymentMethodType>  $allowedMethods
     * @param  ?PayoutRecipientUpdate  $recipient
     * @phpstan-pure
     */
    public function __construct(?array $allowedMethods = null, ?PayoutRecipientUpdate $recipient = null)
    {
        $this->allowedMethods = $allowedMethods;
        $this->recipient = $recipient;
    }
}