<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class PaymentLinkPayoutDetails
{
    /**
     * A list of payment methods that should be supported for this payment link.
     *
     * @var array<\Moov\MoovPhp\Models\Components\DisbursementPaymentMethodType> $allowedMethods
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allowedMethods')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Moov\MoovPhp\Models\Components\DisbursementPaymentMethodType>')]
    public array $allowedMethods;

    /**
     * Specify the intended recipient of the payout.
     *
     * Either `email` or `phone` must be specified, but not both.
     *
     * This information will be used to authenticate the end user when they follow the payment link.
     *
     * @var \Moov\MoovPhp\Models\Components\PayoutRecipient $recipient
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recipient')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PayoutRecipient')]
    public PayoutRecipient $recipient;

    /**
     * Optional free-form metadata for the transfer.
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  array<\Moov\MoovPhp\Models\Components\DisbursementPaymentMethodType>  $allowedMethods
     * @param  \Moov\MoovPhp\Models\Components\PayoutRecipient  $recipient
     * @param  ?array<string, string>  $metadata
     * @phpstan-pure
     */
    public function __construct(array $allowedMethods, PayoutRecipient $recipient, ?array $metadata = null)
    {
        $this->allowedMethods = $allowedMethods;
        $this->recipient = $recipient;
        $this->metadata = $metadata;
    }
}