<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** PaymentLinkLineItem - Represents a single line item in a payment link, including optional modifiers and quantity. */
class PaymentLinkLineItem
{
    /**
     * The name of the item.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * The base price of the item before applying option modifiers.
     *
     * @var AmountDecimal $basePrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('basePrice')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\AmountDecimal')]
    public AmountDecimal $basePrice;

    /**
     * The quantity of this item.
     *
     * @var int $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    public int $quantity;

    /**
     * Optional list of modifiers applied to this item (e.g., toppings, upgrades, customizations).
     *
     * @var ?array<PaymentLinkLineItemOption> $options
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('options')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Moov\MoovPhp\Models\Components\PaymentLinkLineItemOption>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $options = null;

    /**
     * Optional unique identifier associating the line item with a product.
     *
     * @var ?string $productID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('productID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $productID = null;

    /**
     * @param  string  $name
     * @param  AmountDecimal  $basePrice
     * @param  int  $quantity
     * @param  ?array<PaymentLinkLineItemOption>  $options
     * @param  ?string  $productID
     * @phpstan-pure
     */
    public function __construct(string $name, AmountDecimal $basePrice, int $quantity, ?array $options = null, ?string $productID = null)
    {
        $this->name = $name;
        $this->basePrice = $basePrice;
        $this->quantity = $quantity;
        $this->options = $options;
        $this->productID = $productID;
    }
}