<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class PayoutDetailsError
{
    /**
     *
     * @var ?string $allowedMethods
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allowedMethods')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $allowedMethods = null;

    /**
     *
     * @var ?\Moov\MoovPhp\Models\Components\PayoutRecipientError $recipient
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recipient')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PayoutRecipientError|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PayoutRecipientError $recipient = null;

    /**
     *
     * @var ?string $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $metadata = null;

    /**
     *
     * @var ?\Moov\MoovPhp\Models\Components\PushOptionsError $pushOptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pushOptions')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PushOptionsError|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PushOptionsError $pushOptions = null;

    /**
     *
     * @var ?string $feePaidBy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('feePaidBy')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $feePaidBy = null;

    /**
     * @param  ?string  $allowedMethods
     * @param  ?\Moov\MoovPhp\Models\Components\PayoutRecipientError  $recipient
     * @param  ?string  $metadata
     * @param  ?\Moov\MoovPhp\Models\Components\PushOptionsError  $pushOptions
     * @param  ?string  $feePaidBy
     * @phpstan-pure
     */
    public function __construct(?string $allowedMethods = null, ?PayoutRecipientError $recipient = null, ?string $metadata = null, ?PushOptionsError $pushOptions = null, ?string $feePaidBy = null)
    {
        $this->allowedMethods = $allowedMethods;
        $this->recipient = $recipient;
        $this->metadata = $metadata;
        $this->pushOptions = $pushOptions;
        $this->feePaidBy = $feePaidBy;
    }
}