<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class ProductOptionGroupValidationError
{
    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     *
     * @var ?string $minSelect
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('minSelect')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $minSelect = null;

    /**
     *
     * @var ?string $maxSelect
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maxSelect')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $maxSelect = null;

    /**
     * $options
     *
     * @var ?array<string, ProductOptionValidationError> $options
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('options')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, \Moov\MoovPhp\Models\Components\ProductOptionValidationError>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $options = null;

    /**
     * @param  ?string  $name
     * @param  ?string  $description
     * @param  ?string  $minSelect
     * @param  ?string  $maxSelect
     * @param  ?array<string, ProductOptionValidationError>  $options
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?string $description = null, ?string $minSelect = null, ?string $maxSelect = null, ?array $options = null)
    {
        $this->name = $name;
        $this->description = $description;
        $this->minSelect = $minSelect;
        $this->maxSelect = $maxSelect;
        $this->options = $options;
    }
}