<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** ProductRequest - Request to create or update a product. */
class ProductRequest
{
    /**
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     * A product's starting price, before applying modifiers.
     *
     * @var \Moov\MoovPhp\Models\Components\AmountDecimal $basePrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('basePrice')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\AmountDecimal')]
    public AmountDecimal $basePrice;

    /**
     * A detailed description of the product.
     *
     *
     * - Must be valid UTF-8 text
     * - Supports Markdown for formatting
     * - HTML is not permitted and will be rejected
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Whether applicable tax rules may be applied to this product. True does not guarantee tax is charged; false excludes the product from tax calculation. Omitted values default to true on creation and preserve the existing setting on update.
     *
     * @var ?bool $isTaxable
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('isTaxable')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isTaxable = null;

    /**
     * Assign previously uploaded images to a product or option.
     *
     * @var ?array<\Moov\MoovPhp\Models\Components\AssignProductImage> $images
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('images')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Moov\MoovPhp\Models\Components\AssignProductImage>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $images = null;

    /**
     * Optional configuration options for a product, such as size or color.
     *
     * @var ?array<\Moov\MoovPhp\Models\Components\CreateProductOptionGroup> $optionGroups
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('optionGroups')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Moov\MoovPhp\Models\Components\CreateProductOptionGroup>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $optionGroups = null;

    /**
     * The ID of a product taxonomy category to associate with the product.
     *
     * @var ?string $categoryID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('categoryID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $categoryID = null;

    /**
     * @param  string  $title
     * @param  \Moov\MoovPhp\Models\Components\AmountDecimal  $basePrice
     * @param  ?string  $description
     * @param  ?bool  $isTaxable
     * @param  ?array<\Moov\MoovPhp\Models\Components\AssignProductImage>  $images
     * @param  ?array<\Moov\MoovPhp\Models\Components\CreateProductOptionGroup>  $optionGroups
     * @param  ?string  $categoryID
     * @phpstan-pure
     */
    public function __construct(string $title, AmountDecimal $basePrice, ?string $description = null, ?bool $isTaxable = null, ?array $images = null, ?array $optionGroups = null, ?string $categoryID = null)
    {
        $this->title = $title;
        $this->basePrice = $basePrice;
        $this->description = $description;
        $this->isTaxable = $isTaxable;
        $this->images = $images;
        $this->optionGroups = $optionGroups;
        $this->categoryID = $categoryID;
    }
}