<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


/** Profile - Describes a Moov account profile. A profile will have a business or an individual, depending on the account's type. */
class Profile
{
    /**
     * Describes an individual.
     *
     * @var ?IndividualProfile $individual
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('individual')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\OpenAPI\Models\Components\IndividualProfile|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?IndividualProfile $individual = null;

    /**
     * Describes a business.
     *
     * @var ?BusinessProfile $business
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\OpenAPI\Models\Components\BusinessProfile|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BusinessProfile $business = null;

    /**
     * @param  ?IndividualProfile  $individual
     * @param  ?BusinessProfile  $business
     * @phpstan-pure
     */
    public function __construct(?IndividualProfile $individual = null, ?BusinessProfile $business = null)
    {
        $this->individual = $individual;
        $this->business = $business;
    }
}