<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class PullFromCardTransferProcessingDetails
{
    /**
     *
     * @var ?string $authorizationCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorizationCode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $authorizationCode = null;

    /**
     *
     * @var ?string $networkTransactionID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('networkTransactionID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $networkTransactionID = null;

    /**
     *
     * @var ?string $networkResponseCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('networkResponseCode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $networkResponseCode = null;

    /**
     *
     * @var ?\Moov\MoovPhp\Models\Components\CardTransactionFailureCode $failureCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('failureCode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\CardTransactionFailureCode|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CardTransactionFailureCode $failureCode = null;

    /**
     * @param  ?string  $authorizationCode
     * @param  ?string  $networkTransactionID
     * @param  ?string  $networkResponseCode
     * @param  ?\Moov\MoovPhp\Models\Components\CardTransactionFailureCode  $failureCode
     * @phpstan-pure
     */
    public function __construct(?string $authorizationCode = null, ?string $networkTransactionID = null, ?string $networkResponseCode = null, ?CardTransactionFailureCode $failureCode = null)
    {
        $this->authorizationCode = $authorizationCode;
        $this->networkTransactionID = $networkTransactionID;
        $this->networkResponseCode = $networkResponseCode;
        $this->failureCode = $failureCode;
    }
}