<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


/**
 * The rejection code of an RTP transaction that caused the bank account status to change.
 *
 *
 * - AC03: Account Invalid
 * - AC04: Account Closed
 * - AC06: Account Blocked
 * - AC14: Creditor Account Type Invalid
 * - AG01: Transactions Forbidden On Account
 * - AG03: Transaction Type Not Supported
 * - MD07: Customer Deceased
 */
enum RTPRejectionCode: string
{
    case Ac03 = 'AC03';
    case Ac04 = 'AC04';
    case Ac06 = 'AC06';
    case Ac14 = 'AC14';
    case Ag01 = 'AG01';
    case Ag03 = 'AG03';
    case Md07 = 'MD07';
}
