<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


/** RTPTransactionDetails - RTP specific details about the transaction. */
class RTPTransactionDetails
{
    /**
     * Status of a transaction within the RTP lifecycle.
     *
     * @var RTPTransactionStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\OpenAPI\Models\Components\RTPTransactionStatus')]
    public RTPTransactionStatus $status;

    /**
     * Response code returned by network on failure.
     *
     * @var ?string $networkResponseCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('networkResponseCode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $networkResponseCode = null;

    /**
     * Status codes for RTP failures.
     *
     * @var ?RTPFailureCode $failureCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('failureCode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\OpenAPI\Models\Components\RTPFailureCode|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?RTPFailureCode $failureCode = null;

    /**
     *
     * @var ?\DateTime $initiatedOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('initiatedOn')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $initiatedOn = null;

    /**
     *
     * @var ?\DateTime $completedOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('completedOn')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $completedOn = null;

    /**
     *
     * @var ?\DateTime $failedOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('failedOn')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $failedOn = null;

    /**
     *
     * @var ?\DateTime $acceptedWithoutPostingOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('acceptedWithoutPostingOn')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $acceptedWithoutPostingOn = null;

    /**
     * @param  RTPTransactionStatus  $status
     * @param  ?string  $networkResponseCode
     * @param  ?RTPFailureCode  $failureCode
     * @param  ?\DateTime  $initiatedOn
     * @param  ?\DateTime  $completedOn
     * @param  ?\DateTime  $failedOn
     * @param  ?\DateTime  $acceptedWithoutPostingOn
     */
    public function __construct(RTPTransactionStatus $status, ?string $networkResponseCode = null, ?RTPFailureCode $failureCode = null, ?\DateTime $initiatedOn = null, ?\DateTime $completedOn = null, ?\DateTime $failedOn = null, ?\DateTime $acceptedWithoutPostingOn = null)
    {
        $this->status = $status;
        $this->networkResponseCode = $networkResponseCode;
        $this->failureCode = $failureCode;
        $this->initiatedOn = $initiatedOn;
        $this->completedOn = $completedOn;
        $this->failedOn = $failedOn;
        $this->acceptedWithoutPostingOn = $acceptedWithoutPostingOn;
    }
}