<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** RunTransfer - Defines the attributes of a transfer. */
class RunTransfer
{
    /**
     *
     * @var Amount $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\Amount')]
    public Amount $amount;

    /**
     *
     * @var SchedulePaymentMethod $destination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\SchedulePaymentMethod')]
    public SchedulePaymentMethod $destination;

    /**
     *
     * @var string $partnerAccountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('partnerAccountID')]
    public string $partnerAccountID;

    /**
     *
     * @var SchedulePaymentMethod $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\SchedulePaymentMethod')]
    public SchedulePaymentMethod $source;

    /**
     * Simple description to place on the transfer.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Optional sales tax amount. This amount is included in the total transfer amount.
     *
     * @var ?Amount $salesTaxAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('salesTaxAmount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\Amount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Amount $salesTaxAmount = null;

    /**
     * An optional collection of line items for a scheduled transfer.
     *
     * When line items are provided their total must equal `amount` minus `salesTaxAmount`.
     *
     * @var ?ScheduledTransferLineItems $lineItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lineItems')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\ScheduledTransferLineItems|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ScheduledTransferLineItems $lineItems = null;

    /**
     * @param  Amount  $amount
     * @param  SchedulePaymentMethod  $destination
     * @param  string  $partnerAccountID
     * @param  SchedulePaymentMethod  $source
     * @param  string  $description
     * @param  ?Amount  $salesTaxAmount
     * @param  ?ScheduledTransferLineItems  $lineItems
     * @phpstan-pure
     */
    public function __construct(Amount $amount, SchedulePaymentMethod $destination, string $partnerAccountID, SchedulePaymentMethod $source, string $description, ?Amount $salesTaxAmount = null, ?ScheduledTransferLineItems $lineItems = null)
    {
        $this->amount = $amount;
        $this->destination = $destination;
        $this->partnerAccountID = $partnerAccountID;
        $this->source = $source;
        $this->description = $description;
        $this->salesTaxAmount = $salesTaxAmount;
        $this->lineItems = $lineItems;
    }
}