<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class ScheduledTransferImageMetadata
{
    /**
     * Unique identifier for a image resource.
     *
     * @var string $imageID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('imageID')]
    public string $imageID;

    /**
     * The image's public URL.
     *
     * @var string $link
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('link')]
    public string $link;

    /**
     * A unique identifier for an image, used in public image links.
     *
     * @var string $publicID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('publicID')]
    public string $publicID;

    /**
     * Alternative text for the image.
     *
     * @var ?string $altText
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('altText')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $altText = null;

    /**
     * @param  string  $imageID
     * @param  string  $link
     * @param  string  $publicID
     * @param  ?string  $altText
     * @phpstan-pure
     */
    public function __construct(string $imageID, string $link, string $publicID, ?string $altText = null)
    {
        $this->imageID = $imageID;
        $this->link = $link;
        $this->publicID = $publicID;
        $this->altText = $altText;
    }
}