<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** ScheduledTransferLineItems - Line items for a scheduled transfer. */
class ScheduledTransferLineItems
{
    /**
     * The list of line items.
     *
     * @var array<ScheduledTransferLineItem> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Moov\MoovPhp\Models\Components\ScheduledTransferLineItem>')]
    public array $items;

    /**
     * @param  array<ScheduledTransferLineItem>  $items
     * @phpstan-pure
     */
    public function __construct(array $items)
    {
        $this->items = $items;
    }
}