<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class ScheduleWindowError
{
    /**
     *
     * @var ?string $days
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('days')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $days = null;

    /**
     *
     * @var ?string $startTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('startTime')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $startTime = null;

    /**
     *
     * @var ?string $endTime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('endTime')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $endTime = null;

    /**
     * @param  ?string  $days
     * @param  ?string  $startTime
     * @param  ?string  $endTime
     * @phpstan-pure
     */
    public function __construct(?string $days = null, ?string $startTime = null, ?string $endTime = null)
    {
        $this->days = $days;
        $this->startTime = $startTime;
        $this->endTime = $endTime;
    }
}