<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class SendFunds
{
    /**
     *
     * @var ?SendFundsAch $ach
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ach')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\SendFundsAch|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SendFundsAch $ach = null;

    /**
     *
     * @var ?SendFundsPushToCard $pushToCard
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pushToCard')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\SendFundsPushToCard|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SendFundsPushToCard $pushToCard = null;

    /**
     *
     * @var ?SendFundsRtp $rtp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rtp')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\SendFundsRtp|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SendFundsRtp $rtp = null;

    /**
     * @param  ?SendFundsAch  $ach
     * @param  ?SendFundsPushToCard  $pushToCard
     * @param  ?SendFundsRtp  $rtp
     * @phpstan-pure
     */
    public function __construct(?SendFundsAch $ach = null, ?SendFundsPushToCard $pushToCard = null, ?SendFundsRtp $rtp = null)
    {
        $this->ach = $ach;
        $this->pushToCard = $pushToCard;
        $this->rtp = $rtp;
    }
}