<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\OpenAPI\Models\Components;


/** Settings - User provided settings to manage an account. */
class Settings
{
    /**
     * User provided settings to manage card payments. This data is only allowed on a business account.
     *
     * @var ?CardPaymentSettings $cardPayment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cardPayment')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\OpenAPI\Models\Components\CardPaymentSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CardPaymentSettings $cardPayment = null;

    /**
     *
     * @var ?ACHPaymentSettings $achPayment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('achPayment')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\OpenAPI\Models\Components\ACHPaymentSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ACHPaymentSettings $achPayment = null;

    /**
     * @param  ?CardPaymentSettings  $cardPayment
     * @param  ?ACHPaymentSettings  $achPayment
     * @phpstan-pure
     */
    public function __construct(?CardPaymentSettings $cardPayment = null, ?ACHPaymentSettings $achPayment = null)
    {
        $this->cardPayment = $cardPayment;
        $this->achPayment = $achPayment;
    }
}