<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** TaxID - An EIN (employer identification number) for the business. For sole proprietors, an SSN can be used as the EIN. */
class TaxID
{
    /**
     *
     * @var Ein $ein
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ein')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\Ein')]
    public Ein $ein;

    /**
     * @param  Ein  $ein
     * @phpstan-pure
     */
    public function __construct(Ein $ein)
    {
        $this->ein = $ein;
    }
}