<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/**
 * Defines which amount should be used when calculating the final payment total. This calculation applies for percentage tip values.
 *
 * - `pre-tax`: Tip amounts are calculated using the subtotal amount before taxes
 * - `post-tax`: Tip amounts are calculated using the subtotal amount + taxes
 */
enum TipCalculationBasis: string
{
    case PreTax = 'pre-tax';
    case PostTax = 'post-tax';
}
