<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class TransferEventDisputeDetails
{
    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     *
     * @var string $disputeID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('disputeID')]
    public string $disputeID;

    /**
     * The phase of a dispute within the dispute lifecycle.
     *
     * @var \Moov\MoovPhp\Models\Components\DisputePhase $phase
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phase')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\DisputePhase')]
    public DisputePhase $phase;

    /**
     * The status of a particular dispute. 
     *
     *
     * Read our [disputes guide](https://docs.moov.io/guides/money-movement/accept-payments/card-acceptance/disputes/#dispute-statuses) to learn what each status means.
     *
     * @var \Moov\MoovPhp\Models\Components\DisputeStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\DisputeStatus')]
    public DisputeStatus $status;

    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     *
     * @var ?string $captureID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('captureID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $captureID = null;

    /**
     * @param  string  $disputeID
     * @param  \Moov\MoovPhp\Models\Components\DisputePhase  $phase
     * @param  \Moov\MoovPhp\Models\Components\DisputeStatus  $status
     * @param  ?string  $captureID
     * @phpstan-pure
     */
    public function __construct(string $disputeID, DisputePhase $phase, DisputeStatus $status, ?string $captureID = null)
    {
        $this->disputeID = $disputeID;
        $this->phase = $phase;
        $this->status = $status;
        $this->captureID = $captureID;
    }
}