<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class TransferOptions
{
    /**
     * $sourceOptions
     *
     * @var ?array<MoovWalletTransferPaymentMethod|AchDebitFundTransferPaymentMethod|AchDebitCollectTransferPaymentMethod|AchCreditStandardTransferPaymentMethod|AchCreditSameDayTransferPaymentMethod|RtpCreditTransferPaymentMethod|CardPaymentTransferPaymentMethod|PushToCardTransferPaymentMethod|PullFromCardTransferPaymentMethod|ApplePayTransferPaymentMethod|CardPresentPaymentTransferPaymentMethod> $sourceOptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sourceOptions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Moov\MoovPhp\Models\Components\MoovWalletTransferPaymentMethod|\Moov\MoovPhp\Models\Components\AchDebitFundTransferPaymentMethod|\Moov\MoovPhp\Models\Components\AchDebitCollectTransferPaymentMethod|\Moov\MoovPhp\Models\Components\AchCreditStandardTransferPaymentMethod|\Moov\MoovPhp\Models\Components\AchCreditSameDayTransferPaymentMethod|\Moov\MoovPhp\Models\Components\RtpCreditTransferPaymentMethod|\Moov\MoovPhp\Models\Components\CardPaymentTransferPaymentMethod|\Moov\MoovPhp\Models\Components\PushToCardTransferPaymentMethod|\Moov\MoovPhp\Models\Components\PullFromCardTransferPaymentMethod|\Moov\MoovPhp\Models\Components\ApplePayTransferPaymentMethod|\Moov\MoovPhp\Models\Components\CardPresentPaymentTransferPaymentMethod>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $sourceOptions = null;

    /**
     * $destinationOptions
     *
     * @var ?array<MoovWalletTransferPaymentMethod|AchDebitFundTransferPaymentMethod|AchDebitCollectTransferPaymentMethod|AchCreditStandardTransferPaymentMethod|AchCreditSameDayTransferPaymentMethod|RtpCreditTransferPaymentMethod|CardPaymentTransferPaymentMethod|PushToCardTransferPaymentMethod|PullFromCardTransferPaymentMethod|ApplePayTransferPaymentMethod|CardPresentPaymentTransferPaymentMethod> $destinationOptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destinationOptions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Moov\MoovPhp\Models\Components\MoovWalletTransferPaymentMethod|\Moov\MoovPhp\Models\Components\AchDebitFundTransferPaymentMethod|\Moov\MoovPhp\Models\Components\AchDebitCollectTransferPaymentMethod|\Moov\MoovPhp\Models\Components\AchCreditStandardTransferPaymentMethod|\Moov\MoovPhp\Models\Components\AchCreditSameDayTransferPaymentMethod|\Moov\MoovPhp\Models\Components\RtpCreditTransferPaymentMethod|\Moov\MoovPhp\Models\Components\CardPaymentTransferPaymentMethod|\Moov\MoovPhp\Models\Components\PushToCardTransferPaymentMethod|\Moov\MoovPhp\Models\Components\PullFromCardTransferPaymentMethod|\Moov\MoovPhp\Models\Components\ApplePayTransferPaymentMethod|\Moov\MoovPhp\Models\Components\CardPresentPaymentTransferPaymentMethod>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $destinationOptions = null;

    /**
     * @param  ?array<MoovWalletTransferPaymentMethod|AchDebitFundTransferPaymentMethod|AchDebitCollectTransferPaymentMethod|AchCreditStandardTransferPaymentMethod|AchCreditSameDayTransferPaymentMethod|RtpCreditTransferPaymentMethod|CardPaymentTransferPaymentMethod|PushToCardTransferPaymentMethod|PullFromCardTransferPaymentMethod|ApplePayTransferPaymentMethod|CardPresentPaymentTransferPaymentMethod>  $sourceOptions
     * @param  ?array<MoovWalletTransferPaymentMethod|AchDebitFundTransferPaymentMethod|AchDebitCollectTransferPaymentMethod|AchCreditStandardTransferPaymentMethod|AchCreditSameDayTransferPaymentMethod|RtpCreditTransferPaymentMethod|CardPaymentTransferPaymentMethod|PushToCardTransferPaymentMethod|PullFromCardTransferPaymentMethod|ApplePayTransferPaymentMethod|CardPresentPaymentTransferPaymentMethod>  $destinationOptions
     * @phpstan-pure
     */
    public function __construct(?array $sourceOptions = null, ?array $destinationOptions = null)
    {
        $this->sourceOptions = $sourceOptions;
        $this->destinationOptions = $destinationOptions;
    }
}