<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class TransferEventInstantBankCreditDetails
{
    /**
     * Status of a transaction within the instant-bank lifecycle.
     *
     * @var \Moov\MoovPhp\Models\Components\InstantBankTransactionStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\InstantBankTransactionStatus')]
    public InstantBankTransactionStatus $status;

    /**
     * Status codes for instant-bank failures.
     *
     * @var ?\Moov\MoovPhp\Models\Components\InstantBankFailureCode $failureCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('failureCode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\InstantBankFailureCode|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?InstantBankFailureCode $failureCode = null;

    /**
     * @param  \Moov\MoovPhp\Models\Components\InstantBankTransactionStatus  $status
     * @param  ?\Moov\MoovPhp\Models\Components\InstantBankFailureCode  $failureCode
     * @phpstan-pure
     */
    public function __construct(InstantBankTransactionStatus $status, ?InstantBankFailureCode $failureCode = null)
    {
        $this->status = $status;
        $this->failureCode = $failureCode;
    }
}