<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/**
 * TransferLineItems - An optional collection of line items for a transfer.
 *
 * When line items are provided, their total plus sales tax must equal the transfer amount.
 */
class TransferLineItems
{
    /**
     * The list of line items.
     *
     * @var array<TransferLineItem> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Moov\MoovPhp\Models\Components\TransferLineItem>')]
    public array $items;

    /**
     * @param  array<TransferLineItem>  $items
     * @phpstan-pure
     */
    public function __construct(array $items)
    {
        $this->items = $items;
    }
}