<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** The rail and direction used to move funds for a transfer. */
enum TransferType: string
{
    case CardPayment = 'card-payment';
    case PushToCard = 'push-to-card';
    case PullFromCard = 'pull-from-card';
    case AchDebit = 'ach-debit';
    case AchCredit = 'ach-credit';
    case AchDebitToAchCredit = 'ach-debit-to-ach-credit';
    case InstantBankCredit = 'instant-bank-credit';
    case Wallet = 'wallet';
}
