<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class UpdatePaymentLink
{
    /**
     *
     * @var ?AmountUpdate $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\AmountUpdate|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AmountUpdate $amount = null;

    /**
     *
     * @var ?AmountUpdate $salesTaxAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('salesTaxAmount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\AmountUpdate|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AmountUpdate $salesTaxAmount = null;

    /**
     * Customizable display options for a payment link.
     *
     * @var ?PaymentLinkDisplayOptionsUpdate $display
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('display')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PaymentLinkDisplayOptionsUpdate|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentLinkDisplayOptionsUpdate $display = null;

    /**
     *
     * @var ?PaymentLinkCustomerOptions $customer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PaymentLinkCustomerOptions|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentLinkCustomerOptions $customer = null;

    /**
     * Options for payment links used to collect payment.
     *
     * @var ?PaymentLinkPaymentDetailsUpdate $payment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PaymentLinkPaymentDetailsUpdate|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentLinkPaymentDetailsUpdate $payment = null;

    /**
     *
     * @var ?PaymentLinkPayoutDetailsUpdate $payout
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payout')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\PaymentLinkPayoutDetailsUpdate|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentLinkPayoutDetailsUpdate $payout = null;

    /**
     * An optional collection of line items for a payment link.
     *
     * When line items are provided, their total plus sales tax must equal the payment link amount.
     *
     * @var ?CreatePaymentLinkLineItemsUpdate $lineItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lineItems')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\CreatePaymentLinkLineItemsUpdate|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreatePaymentLinkLineItemsUpdate $lineItems = null;

    /**
     *
     * @var ?\DateTime $expiresOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expiresOn')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $expiresOn = null;

    /**
     * @param  ?AmountUpdate  $amount
     * @param  ?AmountUpdate  $salesTaxAmount
     * @param  ?PaymentLinkDisplayOptionsUpdate  $display
     * @param  ?PaymentLinkCustomerOptions  $customer
     * @param  ?PaymentLinkPaymentDetailsUpdate  $payment
     * @param  ?PaymentLinkPayoutDetailsUpdate  $payout
     * @param  ?CreatePaymentLinkLineItemsUpdate  $lineItems
     * @param  ?\DateTime  $expiresOn
     * @phpstan-pure
     */
    public function __construct(?AmountUpdate $amount = null, ?AmountUpdate $salesTaxAmount = null, ?PaymentLinkDisplayOptionsUpdate $display = null, ?PaymentLinkCustomerOptions $customer = null, ?PaymentLinkPaymentDetailsUpdate $payment = null, ?PaymentLinkPayoutDetailsUpdate $payout = null, ?CreatePaymentLinkLineItemsUpdate $lineItems = null, ?\DateTime $expiresOn = null)
    {
        $this->amount = $amount;
        $this->salesTaxAmount = $salesTaxAmount;
        $this->display = $display;
        $this->customer = $customer;
        $this->payment = $payment;
        $this->payout = $payout;
        $this->lineItems = $lineItems;
        $this->expiresOn = $expiresOn;
    }
}