<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class UpdateIssuedCard
{
    /**
     * Updates the state of a Moov issued card.
     *
     * - `closed`: The card is permanently deactivated and cannot approve authorizations. A card can be closed by request or when it expires.
     *
     * @var ?\Moov\MoovPhp\Models\Components\UpdateIssuedCardState $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\UpdateIssuedCardState|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateIssuedCardState $state = null;

    /**
     *
     * @var ?string $nickname
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nickname')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $nickname = null;

    /**
     * $metadata
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     *
     * @var ?\Moov\MoovPhp\Models\Components\BillingAddress $billingAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billingAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\BillingAddress|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BillingAddress $billingAddress = null;

    /**
     * @param  ?\Moov\MoovPhp\Models\Components\UpdateIssuedCardState  $state
     * @param  ?string  $nickname
     * @param  ?array<string, string>  $metadata
     * @param  ?\Moov\MoovPhp\Models\Components\BillingAddress  $billingAddress
     * @phpstan-pure
     */
    public function __construct(?UpdateIssuedCardState $state = null, ?string $nickname = null, ?array $metadata = null, ?BillingAddress $billingAddress = null)
    {
        $this->state = $state;
        $this->nickname = $nickname;
        $this->metadata = $metadata;
        $this->billingAddress = $billingAddress;
    }
}