<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** UpdateIssuingControlsMerchantRestrictions - Replaces the merchant restrictions. Set to `null` to remove. */
class UpdateIssuingControlsMerchantRestrictions
{
    /**
     * Whether the listed merchants are the only ones allowed, or the ones to block.
     *
     * @var ?\Moov\MoovPhp\Models\Components\IssuingControlsRestrictionMode $mode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\IssuingControlsRestrictionMode|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?IssuingControlsRestrictionMode $mode = null;

    /**
     * The merchants to allow or block.
     *
     * @var ?array<\Moov\MoovPhp\Models\Components\MerchantEntry> $merchants
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('merchants')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Moov\MoovPhp\Models\Components\MerchantEntry>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $merchants = null;

    /**
     * @param  ?\Moov\MoovPhp\Models\Components\IssuingControlsRestrictionMode  $mode
     * @param  ?array<\Moov\MoovPhp\Models\Components\MerchantEntry>  $merchants
     * @phpstan-pure
     */
    public function __construct(?IssuingControlsRestrictionMode $mode = null, ?array $merchants = null)
    {
        $this->mode = $mode;
        $this->merchants = $merchants;
    }
}