<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/**
 * Type of a wallet.
 *
 *   - `default`: The system-generated wallet automatically created when an account is granted the wallet capability.
 *   - `general`: An additional, user-defined wallet created via API or Dashboard.
 *   - `card-issuing`: The system-generated wallet automatically created when an account is granted the card-issuing capability.
 */
enum WalletType: string
{
    case Default = 'default';
    case General = 'general';
    case CardIssuing = 'card-issuing';
}
