<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class WalletAvailableBalance
{
    /**
     * A 3-letter ISO 4217 currency code.
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * Quantity in the smallest unit of the specified currency. 
     *
     *
     * In USD this is cents, for example, $12.04 is 1204 and $0.99 is 99.
     *
     * @var int $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public int $value;

    /**
     *
     * @var string $valueDecimal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('valueDecimal')]
    public string $valueDecimal;

    /**
     * @param  string  $currency
     * @param  int  $value
     * @param  string  $valueDecimal
     * @phpstan-pure
     */
    public function __construct(string $currency, int $value, string $valueDecimal)
    {
        $this->currency = $currency;
        $this->value = $value;
        $this->valueDecimal = $valueDecimal;
    }
}