<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class WebhookDataCapabilityUpdated
{
    /**
     *
     * @var string $accountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accountID')]
    public string $accountID;

    /**
     * Moov account capabilities.
     *
     *
     * **Deprecated capabilities**
     *
     * The `send-funds`, `collect-funds`, and `wallet` capability IDs are deprecated. Request granular capabilities instead (for example, `send-funds.ach`, `collect-funds.card-payments`, or `wallet.balance`). Deprecated values will be removed in a future API version.
     *
     * Read our [capabilities reference](https://docs.moov.io/guides/accounts/capabilities/reference/) to choose the right capabilities for your integration.
     *
     * The `production-app`, `platform.production-app`, and / or `platform.wallet-transfers` capabilities might appear in the list for your Partner account. These are read-only capabilities that Moov requests. These capabilities remain active with your account and require no additional action.
     *
     * @var \Moov\MoovPhp\Models\Components\CapabilityID $capabilityID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('capabilityID')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\CapabilityID')]
    public CapabilityID $capabilityID;

    /**
     * The status of the capability requested for an account.
     *
     * @var \Moov\MoovPhp\Models\Components\CapabilityStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\CapabilityStatus')]
    public CapabilityStatus $status;

    /**
     *
     * @var ?string $foreignID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('foreignID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $foreignID = null;

    /**
     * @param  string  $accountID
     * @param  \Moov\MoovPhp\Models\Components\CapabilityID  $capabilityID
     * @param  \Moov\MoovPhp\Models\Components\CapabilityStatus  $status
     * @param  ?string  $foreignID
     * @phpstan-pure
     */
    public function __construct(string $accountID, CapabilityID $capabilityID, CapabilityStatus $status, ?string $foreignID = null)
    {
        $this->accountID = $accountID;
        $this->capabilityID = $capabilityID;
        $this->status = $status;
        $this->foreignID = $foreignID;
    }
}