<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class WebhookDataCardAutoUpdated
{
    /**
     *
     * @var string $cardID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cardID')]
    public string $cardID;

    /**
     *
     * @var string $accountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accountID')]
    public string $accountID;

    /**
     * The results of the card update request.
     *
     * @var CardUpdateReason $updateType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updateType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\CardUpdateReason')]
    public CardUpdateReason $updateType;

    /**
     * @param  string  $cardID
     * @param  string  $accountID
     * @param  CardUpdateReason  $updateType
     * @phpstan-pure
     */
    public function __construct(string $cardID, string $accountID, CardUpdateReason $updateType)
    {
        $this->cardID = $cardID;
        $this->accountID = $accountID;
        $this->updateType = $updateType;
    }
}