<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** WebhookSecret - The secret used to verify webhook payloads. */
class WebhookSecret
{
    /**
     * The secret key used to sign webhook payloads. Use this to verify the authenticity of incoming webhooks.
     *
     * @var string $secret
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('secret')]
    public string $secret;

    /**
     * @param  string  $secret
     * @phpstan-pure
     */
    public function __construct(string $secret)
    {
        $this->secret = $secret;
    }
}