<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class WebhookDataTransferCreated
{
    /**
     * The accountID which facilitated the transfer.
     *
     * @var string $accountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accountID')]
    public string $accountID;

    /**
     *
     * @var string $transferID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transferID')]
    public string $transferID;

    /**
     * Status of a transfer.
     *
     * @var TransferStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\TransferStatus')]
    public TransferStatus $status;

    /**
     * @param  string  $accountID
     * @param  string  $transferID
     * @param  TransferStatus  $status
     * @phpstan-pure
     */
    public function __construct(string $accountID, string $transferID, TransferStatus $status)
    {
        $this->accountID = $accountID;
        $this->transferID = $transferID;
        $this->status = $status;
    }
}