<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class WebhookDataSweepCreated
{
    /**
     *
     * @var string $walletID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('walletID')]
    public string $walletID;

    /**
     *
     * @var string $sweepID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sweepID')]
    public string $sweepID;

    /**
     * @param  string  $walletID
     * @param  string  $sweepID
     * @phpstan-pure
     */
    public function __construct(string $walletID, string $sweepID)
    {
        $this->walletID = $walletID;
        $this->sweepID = $sweepID;
    }
}