<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


class WebhookDataCapabilityRequested
{
    /**
     *
     * @var string $accountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accountID')]
    public string $accountID;

    /**
     * Moov account capabilities.
     *
     *
     * The `production-app`, `platform.production-app`, and / or `platform.wallet-transfers` capabilities might appear in your list. These are read-only capabilities that Moov requests and uses for account verification purposes. These capabilities remains active with your account and require no additional action.
     *
     * @var CapabilityID $capabilityID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('capabilityID')]
    #[\Speakeasy\Serializer\Annotation\Type('\Moov\MoovPhp\Models\Components\CapabilityID')]
    public CapabilityID $capabilityID;

    /**
     *
     * @var ?string $foreignID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('foreignID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $foreignID = null;

    /**
     * @param  string  $accountID
     * @param  CapabilityID  $capabilityID
     * @param  ?string  $foreignID
     * @phpstan-pure
     */
    public function __construct(string $accountID, CapabilityID $capabilityID, ?string $foreignID = null)
    {
        $this->accountID = $accountID;
        $this->capabilityID = $capabilityID;
        $this->foreignID = $foreignID;
    }
}