<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Moov\MoovPhp\Models\Components;


/** Status codes for wire failures. */
enum WireFailureCode: string
{
    case ProcessingError = 'processing-error';
    case InvalidAccount = 'invalid-account';
    case AccountClosed = 'account-closed';
    case AccountBlocked = 'account-blocked';
    case InvalidField = 'invalid-field';
    case TransactionNotSupported = 'transaction-not-supported';
    case LimitExceeded = 'limit-exceeded';
    case InvalidAmount = 'invalid-amount';
    case Other = 'other';
}
